export type ExoticCarPricing = "hourly" | "hourly_range" | "daily";

export type ExoticCarSpec = {
  label: string;
  value: string;
};

export type ExoticCar = {
  id: string;
  name: string;
  section: "hourly" | "daily";
  group: string;
  priceLine: string;
  pricing: ExoticCarPricing;
  priceNote?: string;
  description: string;
  /** Optional bullet points — omit when using specs + requirements only. */
  highlights?: readonly string[];
  /**
   * Gallery slots when using neutral placeholders only (no galleryImages).
   * Ignored when `galleryImages` is set.
   */
  galleryCount?: number;
  /** First image when there is no galleryImages array (single hero). */
  coverImage?: string;
  /** Full photo set — first image is used on cards and as gallery slot 1. */
  galleryImages?: readonly string[];
  specs?: readonly ExoticCarSpec[];
  requirements?: readonly string[];
  /** When set, image placeholders say “Photos coming soon” instead of generic copy. */
  photosComingSoon?: boolean;
  /** Shown first when sort is “Featured first”. */
  featured?: boolean;
  /**
   * Daily listing where chauffeur is also offered — catalog card shows both
   * badges; vehicle is listed under Chauffeur and Self-drive views (deduped in
   * All). Ignored for `section: "hourly"`.
   */
  dualRentalOnCard?: boolean;
  /** With `dualRentalOnCard`, second price line on catalog card (chauffeur). */
  chauffeurPriceLine?: string;
};

const MAYBACH_VAN_BASE_DESCRIPTION =
  "Mercedes-Maybach van with a professional chauffeur — ideal for airport transfers, nights out, and moving a small group in privacy and comfort. Cabin space, rear amenities, and a smooth ride keep every leg of your Miami itinerary relaxed. Final vehicle details and photos are confirmed when you inquire.";

/** Hourly chauffeur fleet groups — add vehicles here. */
export const EXOTIC_CARS_HOURLY_GROUPS: { title: string; cars: ExoticCar[] }[] = [
  {
    title: "Maybach vans",
    cars: [
      {
        id: "maybach-van-royal-blue",
        name: "Maybach van — Royal Blue",
        section: "hourly",
        group: "Maybach",
        priceLine: "$165 / hour",
        pricing: "hourly",
        featured: true,
        description: MAYBACH_VAN_BASE_DESCRIPTION,
        galleryImages: [
          "/exoticcar/chauffeur/royalblue/ROYAL.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-2.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-3.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-4.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-5.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-6.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-7.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-8.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-9.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-10.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-11.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-13.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-14.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-15.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-16.jpg",
          "/exoticcar/chauffeur/royalblue/ROYAL-18.jpg",
        ],
        specs: [
          { label: "Finish", value: "Royal Blue" },
          { label: "Service", value: "Chauffeur only" },
          { label: "Type", value: "Maybach van" },
        ],
        requirements: [
          "Chauffeur service only — self-drive is not available.",
        ],
      },
      {
        id: "maybach-van-tiffany-blue",
        name: "Maybach van — Tiffany Blue",
        section: "hourly",
        group: "Maybach",
        priceLine: "$175 / hour",
        pricing: "hourly",
        description: MAYBACH_VAN_BASE_DESCRIPTION,
        galleryImages: [
          "/exoticcar/chauffeur/tiffanyblue/5STAR-27-2.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-2.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-4.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-5.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-6.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-7.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-8.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-9.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-14.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-15.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-18.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-20.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-23.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-24.jpg",
          "/exoticcar/chauffeur/tiffanyblue/5STAR-28-2.jpg",
        ],
        specs: [
          { label: "Finish", value: "Tiffany Blue" },
          { label: "Service", value: "Chauffeur only" },
          { label: "Type", value: "Maybach van" },
        ],
        requirements: [
          "Chauffeur service only — self-drive is not available.",
        ],
      },
      {
        id: "maybach-van-white",
        name: "Maybach van — White",
        section: "hourly",
        group: "Maybach",
        priceLine: "$175 / hour",
        pricing: "hourly",
        description: MAYBACH_VAN_BASE_DESCRIPTION,
        galleryImages: [
          "/exoticcar/chauffeur/white/WHITE%20VAN.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-3.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-15.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-16.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-17.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-18.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-19.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-20.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-21.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-22.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-23.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-24.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-27.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-28.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-29.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-30.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-31.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-34.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-35.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-36.jpg",
          "/exoticcar/chauffeur/white/WHITE%20VAN-37.jpg",
        ],
        specs: [
          { label: "Finish", value: "White" },
          { label: "Service", value: "Chauffeur only" },
          { label: "Type", value: "Maybach van" },
        ],
        requirements: [
          "Chauffeur service only — self-drive is not available.",
        ],
      },
    ],
  },
  {
    title: "SUV & sprinter",
    cars: [
      {
        id: "chevrolet-suburban-chauffeur",
        name: "Chevrolet Suburban",
        section: "hourly",
        group: "Chevrolet",
        priceLine: "$100 / hour",
        pricing: "hourly",
        priceNote: "Chauffeur service only — driver included. Complimentary snacks with every booking.",
        description:
          "Chauffeur service only at $100 per hour with your driver included. Free snacks are included with every booking. This full-size Chevrolet Suburban moves groups and luggage comfortably across Miami — airport transfers, nights out, and event runs with a smooth, commanding presence.",
        galleryImages: [
          "/exoticcar/chauffeur/chevsuburban/chevsuburban1.jpg",
          "/exoticcar/chauffeur/chevsuburban/chevsuburban2.jpg",
          "/exoticcar/chauffeur/chevsuburban/chevsuburban3.jpg",
          "/exoticcar/chauffeur/chevsuburban/chevsuburban4.jpg",
        ],
        specs: [
          { label: "Brand", value: "Chevrolet" },
          { label: "Model", value: "Suburban" },
          { label: "Service", value: "Chauffeur only (driver included)" },
        ],
        highlights: [
          "Matte black full wrap exterior",
          "Blacked-out multi-spoke wheels",
          "Gold Chevy bowtie badge",
          "Custom fiberoptic starlight headliner",
          "Black leather interior with contrast stitching",
          "Complimentary snacks provided with every booking",
        ],
        requirements: [
          "Chauffeur service only — self-drive is not available.",
        ],
      },
      {
        id: "exclusive-sprinter-chauffeur",
        name: "Exclusive sprinter",
        section: "hourly",
        group: "Sprinter",
        priceLine: "$220 / hour",
        pricing: "hourly",
        priceNote: "Chauffeur service only — driver included.",
        description:
          "Chauffeur service only at $220 per hour with your driver included. This exclusive sprinter is built for VIP group travel in Miami — spacious, private, and finished for arrivals, celebrations, and multi-stop itineraries with comfort from door to door.",
        galleryImages: [
          "/exoticcar/chauffeur/exclusivesprinter/exclusivesprinter1.jpg",
          "/exoticcar/chauffeur/exclusivesprinter/exclusivesprinter2.jpg",
          "/exoticcar/chauffeur/exclusivesprinter/exclusivesprinter3.jpg",
          "/exoticcar/chauffeur/exclusivesprinter/exclusivesprinter4.jpg",
          "/exoticcar/chauffeur/exclusivesprinter/exclusivesprinter5.jpg",
        ],
        specs: [
          { label: "Type", value: "Exclusive sprinter" },
          { label: "Service", value: "Chauffeur only (driver included)" },
        ],
        highlights: [
          "Custom sky blue hexagon-stitched leather captain seats",
          "Reclining seats with footrests",
          "Fiberoptic multicolor starlight ceiling",
          "Geometric LED ceiling light panel",
          "Marble-finish flooring",
          "Privacy window shades",
          "Built-in center console cup holders",
          "Blacked-out exterior with Mercedes Panamericana grille",
        ],
        requirements: [
          "Chauffeur service only — self-drive is not available.",
        ],
      },
    ],
  },
];

const DAILY_PLACEHOLDER_COPY =
  "Full specifications, photos, and rental details are being added. Contact us for availability — the rate shown is indicative and confirmed when you inquire.";

/** Daily self-drive fleet — add vehicles here. */
export const EXOTIC_CARS_DAILY: ExoticCar[] = [
  {
    id: "chevrolet-corvette-c8-stingray",
    name: "Corvette C8 Stingray",
    section: "daily",
    group: "Chevrolet",
    priceLine: "$599 / day",
    pricing: "daily",
    description:
      "Renting the Blue Corvette C8 in Miami gives you modern supercar performance with a sleek, head-turning design. The low stance, sharp lines, and bold blue paint pop against the bayside skyline, grabbing attention on Ocean Drive, Brickell, and every valet drop-off in between. Behind the wheel, precise steering and instant throttle response make quick causeway runs and city traffic feel effortless. The mid-engine layout delivers confident grip and balance, while strong brakes keep everything under control. Inside, you get supportive sport seats, premium materials, and easy-to-use tech for music, navigation, and calls. Choose the Blue C8 when you want a true Miami experience: exotic-level looks, everyday comfort, and the sound of an American V8 echoing off the waterfront.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Coupe" },
      { label: "Color", value: "Blue" },
      { label: "Brand", value: "Chevrolet" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/chevrolet/corvettec8stingray/corvettec8stingray1.webp",
      "/exoticcar/chevrolet/corvettec8stingray/corvettec8stingray2.webp",
    ],
  },
  {
    id: "chevrolet-corvette-z06",
    name: "Corvette Z06",
    section: "daily",
    group: "Chevrolet",
    priceLine: "$699 / day",
    pricing: "daily",
    description:
      "Renting a Corvette Z06 in Miami delivers track-bred excitement with everyday usability. Its sculpted body, wide stance, and distinctive exhaust note draw attention on Ocean Drive and beyond. Precise steering and immediate throttle response make short causeway sprints feel special. Inside, you'll find supportive sport seats, intuitive controls, and modern connectivity for a comfortable cruise. The balanced chassis and strong brakes inspire confidence on city streets or coastal routes. Choose the Z06 if you want American supercar character with sharp dynamics and head-turning style. Experience Miami's energy in a machine designed for performance and presence. The Z06 blends speed, design, and practicality for memorable days and nights in the Magic City.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Coupe" },
      { label: "Color", value: "Black" },
      { label: "Brand", value: "Chevrolet" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/chevrolet/corvettez06/corvettez06-1.webp",
      "/exoticcar/chevrolet/corvettez06/corvettez06-2.webp",
    ],
  },
  {
    id: "chevrolet-corvette-c8",
    name: "Corvette C8",
    section: "daily",
    group: "Chevrolet",
    priceLine: "$599 / day",
    pricing: "daily",
    description:
      "The Chevrolet C8 Corvette is a groundbreaking American sports car, with a mid-engine layout that redefines its performance capabilities. Powered by a 6.2-liter V8 engine, it provides impressive acceleration, offering a mix of power and precision handling. The C8 features an aggressive, aerodynamic design with sharp lines and a modern, driver-focused interior equipped with advanced technology and premium materials. Known for offering supercar-level performance at a more accessible price, the C8 Corvette combines innovation, style, and exhilarating driving dynamics.",
    specs: [
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "495 hp" },
      { label: "Seats", value: "2" },
      { label: "0–60 mph", value: "2.9 sec" },
      { label: "MSRP", value: "$95k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "Security deposit $500–$1000 (confirmed when you book)",
    ],
    galleryImages: [
      "/exoticcar/chevrolet/corvettec8/corvettec8-1.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-2.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-3.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-4.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-5.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-6.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-7.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-8.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-9.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-10.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-11.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-12.jpg",
      "/exoticcar/chevrolet/corvettec8/corvettec8-13.jpg",
    ],
  },

  {
    id: "ferrari-812-superfast",
    name: "Ferrari 812 Superfast",
    section: "daily",
    group: "Ferrari",
    priceLine: "$1999 / day",
    pricing: "daily",
    featured: true,
    description:
      "Renting a Ferrari 812 Superfast presents front-engine V12 prestige at its highest. The long-hood silhouette and commanding stance project authority from hotel forecourt to private events. Power delivery is smooth and abundant, creating effortless speed. The interior offers grand-touring comfort, supportive seats, and thoughtful ergonomics for longer drives. Steering and braking remain precise, giving the 812 a confident, composed feel on city streets and highways. Select the 812 Superfast when you want classic Ferrari presence with modern refinement. It turns every itinerary into a signature moment in Miami.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Coupe" },
      { label: "Color", value: "Black" },
      { label: "Brand", value: "Ferrari" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/ferrari/812superfast/812superfast1.webp",
      "/exoticcar/ferrari/812superfast/812superfast2.webp",
      "/exoticcar/ferrari/812superfast/812superfast3.webp",
      "/exoticcar/ferrari/812superfast/812superfast4.webp",
      "/exoticcar/ferrari/812superfast/812superfast5.webp",
    ],
  },
  {
    id: "ferrari-f8-spider-red",
    name: "Ferrari F8 Spider (Red)",
    section: "daily",
    group: "Ferrari",
    priceLine: "$1799 / day",
    pricing: "daily",
    description:
      "The Ferrari F8 Spider brings mid-engine poise and convertible freedom to Miami. Its retractable hardtop preserves coupe refinement while offering quick access to open-sky driving. Acceleration is instant, and steering feedback is natural and precise. Cabin trim blends carbon accents with fine materials, delivering a modern GT feel. Ride quality remains composed for city use while the chassis is ready for spirited routes when the road opens. Choose the F8 Spider for cutting-edge Ferrari performance with open-top glamour. It's ideal for luxury itineraries, scenic bridges, and sunset arrivals.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Convertible" },
      { label: "Color", value: "Red" },
      { label: "Brand", value: "Ferrari" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/ferrari/f8spiderred/f8spiderred1.webp",
      "/exoticcar/ferrari/f8spiderred/f8spiderred2.webp",
      "/exoticcar/ferrari/f8spiderred/f8spiderred3.webp",
      "/exoticcar/ferrari/f8spiderred/f8spiderred4.webp",
    ],
  },
  {
    id: "ferrari-portofino",
    name: "Ferrari Portofino",
    section: "daily",
    group: "Ferrari",
    priceLine: "$1299 / day",
    pricing: "daily",
    description:
      "A Ferrari Portofino rental brings grand-touring elegance to Miami. With a retractable hardtop, you can switch from coupe calm to open-air glamour in seconds. The long hood, clean lines, and refined exhaust note signal sophisticated performance. The interior mixes Italian craftsmanship with everyday comfort. Supportive seats, intuitive controls, and a compliant ride make longer journeys effortless. Power arrives smoothly, ideal for relaxed boulevard cruising or spirited highway merges. Choose the Portofino for refined Ferrari character and versatile luxury. It suits beachside lunches, gallery openings, and scenic evening drives along the bay.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Convertible" },
      { label: "Color", value: "Black" },
      { label: "Brand", value: "Ferrari" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/ferrari/portofino/portofino1.webp",
      "/exoticcar/ferrari/portofino/portofino2.webp",
      "/exoticcar/ferrari/portofino/portofino3.webp",
      "/exoticcar/ferrari/portofino/portofino4.webp",
    ],
  },
  {
    id: "ferrari-f8-spider-gray",
    name: "Ferrari F8 Spider (Gray)",
    section: "daily",
    group: "Ferrari",
    priceLine: "$1799 / day",
    pricing: "daily",
    description:
      "The Ferrari F8 Spider is a high-performance convertible sports car that combines breathtaking design with exceptional engineering. The F8 Spider offers razor-sharp handling, explosive acceleration, and a sonorous V8 soundtrack, especially rewarding with the roof down. It's a balance of comfort and raw, motorsport-derived excitement.",
    specs: [
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "710 hp" },
      { label: "Seats", value: "2" },
      { label: "0–60 mph", value: "2.9 sec" },
      { label: "MSRP", value: "$445k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/ferrari/f8spidergray/f8spidergray1.jpg",
      "/exoticcar/ferrari/f8spidergray/f8spidergray2.jpg",
      "/exoticcar/ferrari/f8spidergray/f8spidergray3.jpg",
      "/exoticcar/ferrari/f8spidergray/f8spidergray4.jpg",
      "/exoticcar/ferrari/f8spidergray/f8spidergray5.jpg",
      "/exoticcar/ferrari/f8spidergray/f8spidergray6.jpg",
      "/exoticcar/ferrari/f8spidergray/f8spidergray7.jpg",
      "/exoticcar/ferrari/f8spidergray/f8spidergray8.jpg",
      "/exoticcar/ferrari/f8spidergray/f8spidergray9.jpg",
    ],
  },

  {
    id: "tesla-cybertruck",
    name: "Tesla Cybertruck Cyberbeast",
    section: "daily",
    dualRentalOnCard: true,
    group: "Tesla",
    priceLine: "$399 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "Introducing the Tesla Cybertruck Cyberbeast, the ultimate vehicle for those who crave adventure, cutting-edge technology, and a striking presence on the road. This futuristic, all-electric pickup truck redefines off-road capability and urban exploration, making it an ideal rental choice for thrill-seekers and eco-conscious drivers alike. The Cybertruck's angular, stainless-steel exterior is not only a head-turner but also offers a robust dual or tri-motor all-wheel drive system; the Cyberbeast boasts impressive acceleration, going from 0 to 60 mph in as little as 2.9 seconds. Its exceptional torque allows for easy towing and hauling, with a maximum towing capacity of over 14,000 pounds.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "845 hp" },
      { label: "Seats", value: "5" },
      { label: "0–60 mph", value: "2.5 sec" },
      { label: "MSRP", value: "$125k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/tesla/cybertruck/cybertruck1.jpg",
      "/exoticcar/tesla/cybertruck/cybertruck2.jpg",
      "/exoticcar/tesla/cybertruck/cybertruck3.jpg",
      "/exoticcar/tesla/cybertruck/cybertruck4.jpg",
      "/exoticcar/tesla/cybertruck/cybertruck5.jpg",
      "/exoticcar/tesla/cybertruck/cybertruck6.jpg",
      "/exoticcar/tesla/cybertruck/cybertruck7.jpg",
      "/exoticcar/tesla/cybertruck/cybertruck8.jpg",
      "/exoticcar/tesla/cybertruck/cybertruck9.jpg",
      "/exoticcar/tesla/cybertruck/cybertruck10.jpg",
    ],
  },
  {
    id: "bmw-m5",
    name: "BMW M5",
    section: "daily",
    dualRentalOnCard: true,
    group: "BMW",
    priceLine: "$699 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "The 2026 BMW M5 is a high-performance luxury sports sedan that combines supercar-level power with everyday practicality. For the first time in M5 history, it uses a plug-in hybrid powertrain, pairing a 4.4-liter twin-turbo V8 engine with an electric motor to produce about 717 horsepower and 738 lb-ft of torque.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "717 hp" },
      { label: "Seats", value: "5" },
      { label: "0–60 mph", value: "3.4 sec" },
      { label: "MSRP", value: "$140k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/bmw/m5/bmwm5-1.jpg",
      "/exoticcar/bmw/m5/bmwm5-2.jpg",
      "/exoticcar/bmw/m5/bmwm5-3.jpg",
      "/exoticcar/bmw/m5/bmwm5-4.jpg",
      "/exoticcar/bmw/m5/bmwm5-5.jpg",
      "/exoticcar/bmw/m5/bmwm5-6.jpg",
      "/exoticcar/bmw/m5/bmwm5-7.jpg",
      "/exoticcar/bmw/m5/bmwm5-8.jpg",
      "/exoticcar/bmw/m5/bmwm5-9.jpg",
      "/exoticcar/bmw/m5/bmwm5-10.jpg",
      "/exoticcar/bmw/m5/bmwm5-11.jpg",
      "/exoticcar/bmw/m5/bmwm5-12.jpg",
      "/exoticcar/bmw/m5/bmwm5-13.jpg",
      "/exoticcar/bmw/m5/bmwm5-14.jpg",
    ],
  },
  {
    id: "cadillac-escalade",
    name: "Cadillac Escalade",
    section: "daily",
    dualRentalOnCard: true,
    group: "Cadillac",
    priceLine: "$549 / day",
    chauffeurPriceLine: "$125 / hr",
    pricing: "daily",
    featured: true,
    description:
      "The Cadillac Escalade is a full-size luxury SUV that epitomizes opulence and sophistication while offering exceptional space and versatility. As the extended version of the standard Escalade, it features a larger wheelbase, resulting in more interior room, particularly in the cargo area. This SUV is equipped with a powerful V8 engine and advanced driving dynamics for a smooth and confident ride. Inside, the Escalade is adorned with high-quality materials, cutting-edge technology, and premium comfort features, including leather seating, a state-of-the-art infotainment system, and advanced driver-assistance systems. It is ideal for those seeking a luxurious driving experience combined with ample space for passengers and luggage.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$125 / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "420 hp" },
      { label: "Seats", value: "7" },
      { label: "0–60 mph", value: "5.9 sec" },
      { label: "MSRP", value: "$110k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/cadillac/escalade/escalade1.jpg",
      "/exoticcar/cadillac/escalade/escalade2.jpg",
      "/exoticcar/cadillac/escalade/escalade3.jpg",
      "/exoticcar/cadillac/escalade/escalade4.jpg",
      "/exoticcar/cadillac/escalade/escalade5.jpg",
      "/exoticcar/cadillac/escalade/escalade6.jpg",
      "/exoticcar/cadillac/escalade/escalade7.jpg",
      "/exoticcar/cadillac/escalade/escalade8.jpg",
      "/exoticcar/cadillac/escalade/escalade9.jpg",
      "/exoticcar/cadillac/escalade/escalade10.jpg",
      "/exoticcar/cadillac/escalade/escalade11.jpg",
      "/exoticcar/cadillac/escalade/escalade12.jpg",
    ],
  },
  {
    id: "mclaren-gt",
    name: "McLaren GT",
    section: "daily",
    group: "McLaren",
    priceLine: "$999 / day",
    pricing: "daily",
    featured: true,
    description:
      "The McLaren GT is a refined and luxurious grand tourer that blends high performance with everyday usability. It features a powerful 4.0-liter twin-turbocharged V8 engine, producing impressive acceleration and top speeds. With its lightweight carbon fiber chassis, the McLaren GT offers agility and dynamic handling typically found in supercars, yet it's designed for comfort over long distances. The sleek and aerodynamic exterior is coupled with a spacious, elegantly appointed cabin that includes top-tier materials and cutting-edge technology. Offering ample cargo space and a sophisticated ride, the McLaren GT perfectly balances the thrills of a sports car with the practicality of a long-distance tourer, making it a versatile choice for enthusiasts who crave both style and substance.",
    specs: [
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "612 hp" },
      { label: "Seats", value: "2" },
      { label: "0–60 mph", value: "2.8 sec" },
      { label: "MSRP", value: "$255k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/mclaren/gt/mclarengt1.jpg",
      "/exoticcar/mclaren/gt/mclarengt2.jpg",
      "/exoticcar/mclaren/gt/mclarengt3.jpg",
      "/exoticcar/mclaren/gt/mclarengt4.jpg",
      "/exoticcar/mclaren/gt/mclarengt5.jpg",
      "/exoticcar/mclaren/gt/mclarengt6.jpg",
      "/exoticcar/mclaren/gt/mclarengt7.jpg",
      "/exoticcar/mclaren/gt/mclarengt8.jpg",
      "/exoticcar/mclaren/gt/mclarengt9.jpg",
      "/exoticcar/mclaren/gt/mclarengt10.jpg",
    ],
  },
  {
    id: "porsche-911-gt3-blue",
    name: "Porsche 911 GT3 (Blue)",
    section: "daily",
    group: "Porsche",
    priceLine: "$1099 / day",
    pricing: "daily",
    description:
      "The 2024 Porsche 911 GT3 continues to embody Porsche's commitment to precision engineering and track-ready performance, while offering a more accessible entry point into the 911 GT lineup. The GT3's engine is derived from the 911 Speedster, delivering a high-revving experience with a redline up to 9,000 rpm. The PDK transmission offers rapid shifts, while the manual gearbox caters to purists seeking a more engaging driving experience.",
    specs: [
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "502 hp" },
      { label: "Seats", value: "4" },
      { label: "0–60 mph", value: "3.2 sec" },
      { label: "MSRP", value: "$275k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/porsche/911gt3blue/911gt3blue1.jpg",
      "/exoticcar/porsche/911gt3blue/911gt3blue2.jpg",
      "/exoticcar/porsche/911gt3blue/911gt3blue3.jpg",
      "/exoticcar/porsche/911gt3blue/911gt3blue4.jpg",
      "/exoticcar/porsche/911gt3blue/911gt3blue5.jpg",
      "/exoticcar/porsche/911gt3blue/911gt3blue6.jpg",
      "/exoticcar/porsche/911gt3blue/911gt3blue7.jpg",
      "/exoticcar/porsche/911gt3blue/911gt3blue8.jpg",
      "/exoticcar/porsche/911gt3blue/911gt3blue9.jpg",
      "/exoticcar/porsche/911gt3blue/911gt3blue10.jpg",
    ],
  },
  {
    id: "porsche-911-gt3-green",
    name: "Porsche 911 GT3 (Green)",
    section: "daily",
    group: "Porsche",
    priceLine: "$1099 / day",
    pricing: "daily",
    description:
      "The 2024 Porsche 911 GT3 continues to embody Porsche's commitment to precision engineering and track-ready performance, while offering a more accessible entry point into the 911 GT lineup. The GT3's engine is derived from the 911 Speedster, delivering a high-revving experience with a redline up to 9,000 rpm. The PDK transmission offers rapid shifts, while the manual gearbox caters to purists seeking a more engaging driving experience.",
    specs: [
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "502 hp" },
      { label: "Seats", value: "4" },
      { label: "0–60 mph", value: "3.2 sec" },
      { label: "MSRP", value: "$275k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/porsche/911gt3green/911gt3green1.jpg",
      "/exoticcar/porsche/911gt3green/911gt3green2.jpg",
      "/exoticcar/porsche/911gt3green/911gt3green3.jpg",
      "/exoticcar/porsche/911gt3green/911gt3green4.jpg",
      "/exoticcar/porsche/911gt3green/911gt3green5.jpg",
      "/exoticcar/porsche/911gt3green/911gt3green6.jpg",
      "/exoticcar/porsche/911gt3green/911gt3green7.jpg",
      "/exoticcar/porsche/911gt3green/911gt3green8.jpg",
    ],
  },
  {
    id: "porsche-911-turbo-s",
    name: "Porsche 911 Turbo S",
    section: "daily",
    group: "Porsche",
    priceLine: "$1099 / day",
    pricing: "daily",
    featured: true,
    description:
      "The Porsche 911 Turbo S (992) is the high-performance flagship of the 911 lineup, representing the 992 generation of Porsche's iconic rear-engine sports car. It pairs a potent twin-turbocharged flat-six engine (now with advanced T-Hybrid technology and dual electric turbochargers) with an eight-speed PDK gearbox and all-wheel drive, delivering around 700+ hp, blistering acceleration (about 0–100 km/h in ~2.5 s or less), and top speeds near 200 mph (322 km/h)— making it one of the fastest production 911s ever. The Turbo S blends supercar-level performance with everyday usability, refined handling, and luxury features in a classic 911 silhouette.",
    specs: [
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "640 hp" },
      { label: "Seats", value: "2" },
      { label: "0–60 mph", value: "2.5 sec" },
      { label: "MSRP", value: "$275k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/porsche/911turbos/911turbos.jpg",
      "/exoticcar/porsche/911turbos/911turbos1.jpg",
      "/exoticcar/porsche/911turbos/911turbos2.jpg",
      "/exoticcar/porsche/911turbos/911turbos3.jpg",
      "/exoticcar/porsche/911turbos/911turbos4.jpg",
      "/exoticcar/porsche/911turbos/911turbos5.jpg",
      "/exoticcar/porsche/911turbos/911turbos6.jpg",
      "/exoticcar/porsche/911turbos/911turbos7.jpg",
      "/exoticcar/porsche/911turbos/911turbos8.jpg",
      "/exoticcar/porsche/911turbos/911turbos9.jpg",
    ],
  },

  {
    id: "maybach-gls-600-unit-a",
    name: "Maybach GLS 600 (Unit A)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Mercedes",
    priceLine: "$899 / day",
    chauffeurPriceLine: "$175 / hr",
    pricing: "daily",
    description:
      "A Maybach GLS 600 offers lounge-like comfort in an SUV form. The ride is serene, the cabin hushed, and the materials are first-class. Rear seating prioritizes relaxation with generous space and refined amenities. Despite its size, the GLS 600 moves smoothly through city traffic and glides on the highway. The exterior communicates quiet status—ideal for elegant hotel and restaurant arrivals. Choose the Maybach GLS for uncompromising comfort and VIP practicality. It elevates every transfer to a five-star experience.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$175 / hr" },
      { label: "Seats", value: "5+" },
      { label: "Style", value: "SUV" },
      { label: "Color", value: "Black" },
      { label: "Brand", value: "Mercedes" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/mercedes/gls600-a/gls600-a-1.webp",
      "/exoticcar/mercedes/gls600-a/gls600-a-2.webp",
      "/exoticcar/mercedes/gls600-a/gls600-a-3.webp",
      "/exoticcar/mercedes/gls600-a/gls600-a-4.webp",
    ],
  },
  {
    id: "mercedes-g63-light-blue",
    name: "Mercedes-AMG G63 (Light blue)",
    section: "daily",
    group: "Mercedes",
    priceLine: "$799 / day",
    pricing: "daily",
    description:
      "The Mercedes-AMG G63 pairs iconic design with modern luxury. Its elevated seating position, handcrafted interior, and distinctive presence make every arrival feel important. Power is immediate, and the ride is confident across Miami streets. Inside, you'll find premium materials, supportive seating, and strong connectivity for day-to-day convenience. The G63's bold character photographs well and stands out in any setting. Rent the G63 when you want luxury, space, and unmistakable style. It's perfect for groups, events, and photo-ready arrivals.",
    specs: [
      { label: "Seats", value: "5+" },
      { label: "Style", value: "SUV" },
      { label: "Color", value: "Light blue" },
      { label: "Brand", value: "Mercedes" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/mercedes/g63lightblue/g63lightblue1.webp",
      "/exoticcar/mercedes/g63lightblue/g63lightblue2.webp",
      "/exoticcar/mercedes/g63lightblue/g63lightblue3.webp",
    ],
  },
  {
    id: "mercedes-s580-unit-a",
    name: "Mercedes S580 (Unit A)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Mercedes",
    priceLine: "$499 / day",
    chauffeurPriceLine: "$125 / hr",
    pricing: "daily",
    description:
      "An S580 rental is tailored for executive-level comfort. The cabin is whisper-quiet with generous legroom and a refined ride that smooths over city pavement. Ambient lighting and premium audio enhance night cruises and business transfers. Technology supports relaxed driving, while the rear seating area provides space to unwind or work between stops. The exterior communicates understated luxury that suits any venue. Choose the S580 for discreet elegance and first-class comfort. It's the smart pick for meetings, fine dining, and effortless airport runs.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$125 / hr" },
      { label: "Seats", value: "5+" },
      { label: "Style", value: "Sedan" },
      { label: "Color", value: "Black" },
      { label: "Brand", value: "Mercedes" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/mercedes/s580-a/s580-a-1.webp",
      "/exoticcar/mercedes/s580-a/s580-a-2.webp",
    ],
  },
  {
    id: "mercedes-g63-green",
    name: "Mercedes-AMG G63 (Green)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Mercedes",
    priceLine: "$699 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "The Mercedes-Benz G 63 AMG is a bold, high-performance luxury SUV that seamlessly combines iconic design with cutting-edge technology and raw power. Known for its rugged, boxy silhouette that pays homage to the G-Wagen's military roots, the G 63 is a symbol of both opulence and off-road capability. Under the hood, the G 63 is powered by a 4.0-liter twin-turbocharged V8 engine, producing an astounding 577 horsepower and 627 lb-ft of torque. This engine is mated to a 9-speed automatic transmission and features Mercedes' 4MATIC all-wheel-drive system. Thanks to AMG's engineering expertise, the G 63 can accelerate from 0 to 60 mph in just 3.9 seconds, an impressive feat for such a large SUV.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "577 hp" },
      { label: "Seats", value: "5" },
      { label: "0–60 mph", value: "3.9 sec" },
      { label: "MSRP", value: "$230k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/mercedes/g63green/g63green1.webp",
      "/exoticcar/mercedes/g63green/g63green2.webp",
      "/exoticcar/mercedes/g63green/g63green3.webp",
      "/exoticcar/mercedes/g63green/g63green4.webp",
      "/exoticcar/mercedes/g63green/g63green5.webp",
      "/exoticcar/mercedes/g63green/g63green6.webp",
      "/exoticcar/mercedes/g63green/g63green7.webp",
      "/exoticcar/mercedes/g63green/g63green8.webp",
      "/exoticcar/mercedes/g63green/g63green9.webp",
      "/exoticcar/mercedes/g63green/g63green10.jpg",
      "/exoticcar/mercedes/g63green/g63green11.jpg",
    ],
  },
  {
    id: "mercedes-s580-unit-b",
    name: "Mercedes S580 (Unit B)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Mercedes",
    priceLine: "$599 / day",
    chauffeurPriceLine: "$125 / hr",
    pricing: "daily",
    description:
      "The Mercedes-Benz S580 is a top-tier luxury sedan renowned for its blend of performance, technology, and comfort. It features a potent 4.0-liter V8 biturbo engine with mild-hybrid EQ Boost, delivering both impressive power and enhanced fuel efficiency. The S580's interior epitomizes modern opulence, with high-quality materials, advanced infotainment systems, and superior comfort features such as massaging seats and ambient lighting. Its exterior design combines sleek aesthetics with aerodynamic efficiency, embodying the sophistication and refinement expected from the iconic S-Class lineup. The Mercedes-Benz S580 is perfect for those who demand the best in automotive innovation and luxury.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$125 / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "496 hp" },
      { label: "Seats", value: "5" },
      { label: "0–60 mph", value: "3.9 sec" },
      { label: "MSRP", value: "$149k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/mercedes/s580-b/s580-b-1.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-2.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-3.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-4.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-5.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-6.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-7.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-8.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-9.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-10.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-11.jpg",
      "/exoticcar/mercedes/s580-b/s580-b-12.jpg",
    ],
  },
  {
    id: "maybach-s680",
    name: "Mercedes-Maybach S680",
    section: "daily",
    dualRentalOnCard: true,
    group: "Mercedes",
    priceLine: "$849 / day",
    chauffeurPriceLine: "$155 / hr",
    pricing: "daily",
    description:
      "The Mercedes-Maybach S680 is a pinnacle of automotive luxury, combining the timeless elegance of the S-Class with exclusive Maybach refinements. Powered by a robust 4.0-liter V8 biturbo engine with mild-hybrid EQ Boost technology, the S680 seamlessly blends power and efficiency for a supremely smooth driving experience. The interior is a sanctuary of opulence, featuring the finest leather, exquisite wood trims, and cutting-edge technology. Rear passengers are treated to an indulgent experience with executive seating. The Maybach S680 captures the essence of luxury and craftsmanship, catering to those who seek ultimate comfort and sophistication.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$155 / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "496 hp" },
      { label: "Seats", value: "4" },
      { label: "0–60 mph", value: "3.9 sec" },
      { label: "MSRP", value: "$210k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/mercedes/s680/s680-1.jpg",
      "/exoticcar/mercedes/s680/s680-2.jpg",
      "/exoticcar/mercedes/s680/s680-3.jpg",
      "/exoticcar/mercedes/s680/s680-4.jpg",
      "/exoticcar/mercedes/s680/s680-5.jpg",
      "/exoticcar/mercedes/s680/s680-6.jpg",
      "/exoticcar/mercedes/s680/s680-7.jpg",
      "/exoticcar/mercedes/s680/s680-8.jpg",
      "/exoticcar/mercedes/s680/s680-9.jpg",
      "/exoticcar/mercedes/s680/s680-10.jpg",
      "/exoticcar/mercedes/s680/s680-11.jpg",
    ],
  },
  {
    id: "maybach-gls-600-unit-b",
    name: "Maybach GLS 600 (Unit B)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Mercedes",
    priceLine: "$1099 / day",
    chauffeurPriceLine: "$175 / hr",
    pricing: "daily",
    description:
      "The Mercedes-Benz Maybach GLS 600 is the epitome of luxury in the SUV segment. This opulent vehicle combines the commanding presence of an SUV with the unparalleled elegance and craftsmanship of the Maybach brand. Under the hood, it boasts a powerful 4.0-liter V8 biturbo engine with EQ Boost, delivering smooth and effortless performance. The interior is meticulously appointed with the finest materials, including sumptuous leather, wood trim, and state-of-the-art technology. Rear-seat passengers enjoy first-class treatment with features like reclining seats, advanced climate control, and entertainment systems. The Maybach GLS 600 offers an unrivaled blend of luxury, technology, and performance, making it a top choice for those who demand the utmost in automotive excellence.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$175 / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "550 hp" },
      { label: "Seats", value: "4" },
      { label: "0–60 mph", value: "4.2 sec" },
      { label: "MSRP", value: "$210k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/mercedes/gls600-b/gls600-b-1.jpg",
      "/exoticcar/mercedes/gls600-b/gls600-b-2.jpg",
      "/exoticcar/mercedes/gls600-b/gls600-b-3.jpg",
      "/exoticcar/mercedes/gls600-b/gls600-b-4.jpg",
      "/exoticcar/mercedes/gls600-b/gls600-b-5.jpg",
      "/exoticcar/mercedes/gls600-b/gls600-b-6.jpg",
      "/exoticcar/mercedes/gls600-b/gls600-b-7.jpg",
      "/exoticcar/mercedes/gls600-b/gls600-b-8.jpg",
    ],
  },

  {
    id: "rolls-royce-ghost-black-badge",
    name: "Rolls-Royce Ghost Black Badge",
    section: "daily",
    dualRentalOnCard: true,
    group: "Rolls-Royce",
    priceLine: "$1499 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    featured: true,
    description:
      "A Ghost Black Badge rental blends Rolls-Royce refinement with a sport-leaning character. Darker accents and an assertive stance set the tone. On the move, the sedan feels composed and effortlessly quick. Inside, the cabin is minimalist, quiet, and richly finished. Rear accommodations are generous, and the overall experience is tailored to both work and leisure. Choose the Ghost Black Badge to make a confident, contemporary statement. It's ideal for executive agendas and special evenings across the Magic City.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Seats", value: "5+" },
      { label: "Style", value: "Sedan" },
      { label: "Color", value: "Black" },
      { label: "Brand", value: "Rolls-Royce" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/rollsroyce/rrghostblackbadge/rrghostblackbadge1.webp",
      "/exoticcar/rollsroyce/rrghostblackbadge/rrghostblackbadge2.webp",
      "/exoticcar/rollsroyce/rrghostblackbadge/rrghostblackbadge3.webp",
      "/exoticcar/rollsroyce/rrghostblackbadge/rrghostblackbadge4.webp",
      "/exoticcar/rollsroyce/rrghostblackbadge/rrghostblackbadge5.webp",
    ],
  },
  {
    id: "rolls-royce-cullinan-white-unit-a",
    name: "Rolls-Royce Cullinan (White, Unit A)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Rolls-Royce",
    priceLine: "$1399 / day",
    chauffeurPriceLine: "$250-$300 / hr",
    pricing: "daily",
    description:
      "The white Cullinan emphasizes purity and elegance. It photographs beautifully day or night and suits luxury events, weddings, and premium itineraries. The ride remains tranquil, and the interior is thoughtfully finished. Rear seating accommodates guests with generous space and refined amenities. It's a statement vehicle that maintains calm in every situation. Rent the white Cullinan to pair iconic luxury with a clean, modern look. It turns any Miami plan into a first-class experience.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$250-$300 / hr" },
      { label: "Seats", value: "5+" },
      { label: "Style", value: "SUV" },
      { label: "Color", value: "White" },
      { label: "Brand", value: "Rolls-Royce" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/rollsroyce/rrcullinanwhite-a/rrcullinanwhite-a-1.webp",
      "/exoticcar/rollsroyce/rrcullinanwhite-a/rrcullinanwhite-a-2.webp",
      "/exoticcar/rollsroyce/rrcullinanwhite-a/rrcullinanwhite-a-3.webp",
      "/exoticcar/rollsroyce/rrcullinanwhite-a/rrcullinanwhite-a-4.webp",
    ],
  },
  {
    id: "rolls-royce-cullinan-black-unit-a",
    name: "Rolls-Royce Cullinan (Black, Unit A)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Rolls-Royce",
    priceLine: "$1299 / day",
    chauffeurPriceLine: "$250-$300 / hr",
    pricing: "daily",
    description:
      "A Rolls-Royce Cullinan rental elevates your Miami experience with unmatched serenity. The black finish projects authority while the cabin isolates road noise for a calm, unhurried ride. Doors open wide to a spacious, handcrafted interior. Passengers enjoy plush seating, premium audio, and an effortless glide over city streets. Every touchpoint communicates craftsmanship and care. Choose the black Cullinan for VIP transport and standout entrances. It signals sophistication while delivering supreme comfort.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$250-$300 / hr" },
      { label: "Seats", value: "5+" },
      { label: "Style", value: "SUV" },
      { label: "Color", value: "Black" },
      { label: "Brand", value: "Rolls-Royce" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/rollsroyce/rrcullinanblack-a/rrcullinanblack-a-1.webp",
      "/exoticcar/rollsroyce/rrcullinanblack-a/rrcullinanblack-a-2.webp",
      "/exoticcar/rollsroyce/rrcullinanblack-a/rrcullinanblack-a-3.webp",
      "/exoticcar/rollsroyce/rrcullinanblack-a/rrcullinanblack-a-4.webp",
    ],
  },
  {
    id: "rolls-royce-cullinan-white-unit-b",
    name: "Rolls-Royce Cullinan (White, Unit B)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Rolls-Royce",
    priceLine: "$1299 / day",
    chauffeurPriceLine: "$250-$300 / hr",
    pricing: "daily",
    description:
      "The Rolls-Royce Cullinan is the brand's first luxury SUV, embodying the pinnacle of opulence and performance. Named after the largest diamond ever discovered, the Cullinan offers a commanding presence with its bold and elegant design. It features a powerful 6.75-liter V12 engine, providing a silky-smooth, effortless drive. Its lavish interior is adorned with the finest materials, including hand-stitched leather, exquisite wood veneers, and bespoke options. Advanced technology, spacious seating, and state-of-the-art safety features ensure that the Cullinan delivers an unrivaled combination of luxury, comfort, and versatility for both urban and off-road adventures.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$250-$300 / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "563 hp" },
      { label: "Seats", value: "5" },
      { label: "0–60 mph", value: "4.5 sec" },
      { label: "MSRP", value: "$429k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/rollsroyce/rrcullinanwhite-b/rrcullinanwhite-b-1.jpg",
      "/exoticcar/rollsroyce/rrcullinanwhite-b/rrcullinanwhite-b-2.jpg",
      "/exoticcar/rollsroyce/rrcullinanwhite-b/rrcullinanwhite-b-3.jpg",
      "/exoticcar/rollsroyce/rrcullinanwhite-b/rrcullinanwhite-b-4.jpg",
      "/exoticcar/rollsroyce/rrcullinanwhite-b/rrcullinanwhite-b-5.jpg",
      "/exoticcar/rollsroyce/rrcullinanwhite-b/rrcullinanwhite-b-6.jpg",
      "/exoticcar/rollsroyce/rrcullinanwhite-b/rrcullinanwhite-b-7.jpg",
      "/exoticcar/rollsroyce/rrcullinanwhite-b/rrcullinanwhite-b-8.jpg",
      "/exoticcar/rollsroyce/rrcullinanwhite-b/rrcullinanwhite-b-9.jpg",
    ],
  },
  {
    id: "rolls-royce-cullinan-black-unit-b",
    name: "Rolls-Royce Cullinan (Black, Unit B)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Rolls-Royce",
    priceLine: "$1299 / day",
    chauffeurPriceLine: "$250-$300 / hr",
    pricing: "daily",
    description:
      "The Rolls-Royce Cullinan is the brand's first luxury SUV, embodying the pinnacle of opulence and performance. Named after the largest diamond ever discovered, the Cullinan offers a commanding presence with its bold and elegant design. It features a powerful 6.75-liter V12 engine, providing a silky-smooth, effortless drive. Its lavish interior is adorned with the finest materials, including hand-stitched leather, exquisite wood veneers, and bespoke options. Advanced technology, spacious seating, and state-of-the-art safety features ensure that the Cullinan delivers an unrivaled combination of luxury, comfort, and versatility for both urban and off-road adventures.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$250-$300 / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "563 hp" },
      { label: "Seats", value: "5" },
      { label: "0–60 mph", value: "4.5 sec" },
      { label: "MSRP", value: "$429k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/rollsroyce/rrcullinanblack-b/rrcullinanblack-b-1.jpg",
      "/exoticcar/rollsroyce/rrcullinanblack-b/rrcullinanblack-b-2.jpg",
      "/exoticcar/rollsroyce/rrcullinanblack-b/rrcullinanblack-b-3.jpg",
      "/exoticcar/rollsroyce/rrcullinanblack-b/rrcullinanblack-b-4.jpg",
      "/exoticcar/rollsroyce/rrcullinanblack-b/rrcullinanblack-b-5.jpg",
      "/exoticcar/rollsroyce/rrcullinanblack-b/rrcullinanblack-b-6.jpg",
      "/exoticcar/rollsroyce/rrcullinanblack-b/rrcullinanblack-b-7.jpg",
      "/exoticcar/rollsroyce/rrcullinanblack-b/rrcullinanblack-b-8.jpg",
      "/exoticcar/rollsroyce/rrcullinanblack-b/rrcullinanblack-b-9.jpg",
      "/exoticcar/rollsroyce/rrcullinanblack-b/rrcullinanblack-b-10.jpg",
    ],
  },

  // Lamborghini — names & rates only; copy & photos TBD (except where filled in below)
  {
    id: "lamborghini-urus-s-gray",
    name: "Lamborghini Urus S (Gray)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Lamborghini",
    priceLine: "$1199 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "The Urus S refines design and chassis tuning for a sharper, more composed feel. Gray paint highlights crisp bodywork and photographs cleanly in varied light. Steering and suspension updates support agile yet comfortable driving. Inside, expect premium materials, clear displays, and seating for five. It's an easy fit for luxury plans that need both performance and space. Select the Urus S when you want a polished take on the super-SUV formula. It pairs everyday utility with unmistakable Lamborghini style.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Seats", value: "5+" },
      { label: "Style", value: "SUV" },
      { label: "Color", value: "Gray" },
      { label: "Brand", value: "Lamborghini" },
    ],
    galleryImages: [
      "/exoticcar/lamborghini/lamborghiniurussgray/lamborghiniurussgray1.webp",
      "/exoticcar/lamborghini/lamborghiniurussgray/lamborghiniurussgray2.webp",
      "/exoticcar/lamborghini/lamborghiniurussgray/lamborghiniurussgray3.webp",
      "/exoticcar/lamborghini/lamborghiniurussgray/lamborghiniurussgray4.webp",
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
  },
  {
    id: "lamborghini-urus-black",
    name: "Lamborghini Urus (Black)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Lamborghini",
    priceLine: "$999 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "In black, the Urus takes on a stealth, premium look. The dark finish emphasizes its muscular stance and photogenic details. Performance remains immediate, with drive modes that adapt from relaxed cruising to spirited driving. The cabin blends supportive seating with intuitive controls and ample space for companions. It suits day-to-night schedules without compromise. Choose the black Urus for powerful presence and all-around practicality. It's a confident match for upscale venues across the city.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Seats", value: "5+" },
      { label: "Style", value: "SUV" },
      { label: "Color", value: "Black" },
      { label: "Brand", value: "Lamborghini" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/lamborghiniurusblack/lamborghiniurusblack1.png",
      "/exoticcar/lamborghini/lamborghiniurusblack/lamborghiniurusblack2.png",
      "/exoticcar/lamborghini/lamborghiniurusblack/lamborghiniurusblack3.png",
      "/exoticcar/lamborghini/lamborghiniurusblack/lamborghiniurusblack4.png",
    ],
  },
  {
    id: "lamborghini-urus-m-black",
    name: "Lamborghini Urus (M-Black)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Lamborghini",
    priceLine: "$999 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "The Lamborghini Urus combines exotic styling with everyday versatility. In blue, its sharp lines and coupe-inspired roof stand out against Miami's skyline. Acceleration is brisk, steering is quick, and braking is strong. Inside, the Urus seats five with upscale materials and modern tech. Cargo space and ride height make it easy to live with while maintaining supercar drama. Pick the blue Urus for striking visuals and flexible luxury. It's ideal for beach runs, shopping districts, and evening events.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Seats", value: "5+" },
      { label: "Style", value: "SUV" },
      { label: "Color", value: "Blue" },
      { label: "Brand", value: "Lamborghini" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/lamborghiniurusmblack/lamborghiniurusmblack1.png",
      "/exoticcar/lamborghini/lamborghiniurusmblack/lamborghiniurusmblack2.png",
      "/exoticcar/lamborghini/lamborghiniurusmblack/lamborghiniurusmblack3.png",
      "/exoticcar/lamborghini/lamborghiniurusmblack/lamborghiniurusmblack4.png",
    ],
  },
  {
    id: "lamborghini-urus-s-white",
    name: "Lamborghini Urus S (White)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Lamborghini",
    priceLine: "$1199 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "The Lamborghini Urus S is the epitome of luxury and performance, presenting a unique blend of sports car dynamism and the ruggedness of an SUV. As one of Lamborghini's most powerful models, the Urus S combines cutting-edge technology, masterful Italian craftsmanship, and sheer driving pleasure. At the heart of the Urus S is a 4.0-liter twin-turbocharged V8 engine, delivering an astonishing 657 horsepower.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "657 hp" },
      { label: "Seats", value: "4" },
      { label: "0–60 mph", value: "3.2 sec" },
      { label: "MSRP", value: "$290k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/urusswhite/urusswhite1.jpg",
      "/exoticcar/lamborghini/urusswhite/urusswhite2.jpg",
      "/exoticcar/lamborghini/urusswhite/urusswhite3.jpg",
      "/exoticcar/lamborghini/urusswhite/urusswhite4.jpg",
      "/exoticcar/lamborghini/urusswhite/urusswhite5.jpg",
      "/exoticcar/lamborghini/urusswhite/urusswhite6.jpg",
      "/exoticcar/lamborghini/urusswhite/urusswhite7.jpg",
      "/exoticcar/lamborghini/urusswhite/urusswhite8.jpg",
      "/exoticcar/lamborghini/urusswhite/urusswhite9.jpg",
      "/exoticcar/lamborghini/urusswhite/urusswhite10.jpg",
    ],
  },
  {
    id: "lamborghini-urus-se-black",
    name: "Lamborghini Urus SE (Black)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Lamborghini",
    priceLine: "$1299 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "The 2025 Lamborghini Urus SE marks a significant evolution in Lamborghini's lineup, introducing the brand's first plug-in hybrid super SUV. This model combines electrification with Lamborghini's renowned performance and design, delivering a thrilling driving experience. The Urus SE is powered by a twin-turbocharged 4.0-liter V8 engine paired with a 189-horsepower electric motor integrated into the 8-speed automatic transmission. This hybrid setup produces a combined 789 horsepower and 701 lb-ft of torque!",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "789 hp" },
      { label: "Seats", value: "5" },
      { label: "0–60 mph", value: "3.2 sec" },
      { label: "MSRP", value: "$325k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/urusseblack/urusseblack1.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack2.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack3.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack4.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack5.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack6.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack7.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack8.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack9.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack10.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack11.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack12.webp",
      "/exoticcar/lamborghini/urusseblack/urusseblack13.webp",
    ],
  },
  {
    id: "lamborghini-urus-s-lightblue",
    name: "Lamborghini Urus S (LightBlue)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Lamborghini",
    priceLine: "$1199 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "The Blu Cepheus Lamborghini Urus S combines Lamborghini's legendary performance and luxury with an eye-catching and distinct colorway that makes it a true standout on the road. Blu Cepheus is a stunning shade of blue that not only accentuates the bold design features of the Urus but also adds an extra layer of exclusivity and sophistication to this powerful SUV. Underneath the captivating exterior, the Urus S continues to offer unparalleled performance with its 4.0-liter twin-turbocharged V8 engine.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "657 hp" },
      { label: "Seats", value: "5" },
      { label: "0–60 mph", value: "3.2 sec" },
      { label: "MSRP", value: "$310k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/urusslightblue/urusslightblue1.jpg",
      "/exoticcar/lamborghini/urusslightblue/urusslightblue2.jpg",
      "/exoticcar/lamborghini/urusslightblue/urusslightblue3.jpg",
      "/exoticcar/lamborghini/urusslightblue/urusslightblue4.jpg",
      "/exoticcar/lamborghini/urusslightblue/urusslightblue5.jpg",
      "/exoticcar/lamborghini/urusslightblue/urusslightblue6.jpg",
      "/exoticcar/lamborghini/urusslightblue/urusslightblue7.jpg",
      "/exoticcar/lamborghini/urusslightblue/urusslightblue8.jpg",
      "/exoticcar/lamborghini/urusslightblue/urusslightblue9.jpg",
    ],
  },
  {
    id: "lamborghini-huracan-evo-spyder-white",
    name: "Lamborghini Huracan Evo Spyder (white)",
    section: "daily",
    group: "Lamborghini",
    priceLine: "$1399 / day",
    pricing: "daily",
    description:
      "This white Huracan Evo Spyder emphasizes the car's sculpted surfaces and clean, modern look. The light finish photographs beautifully in daylight or under city lights, highlighting every line. Open-air driving enhances the V10 experience while the chassis remains poised and responsive. Inside, premium materials and supportive seating keep you comfortable as you tour Miami's districts. Select the white Evo Spyder for elegant visuals and vivid performance. It creates memorable entrances and striking images wherever you stop.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Convertible" },
      { label: "Color", value: "White" },
      { label: "Brand", value: "Lamborghini" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/hurucanevospyderwhite/huracanevospyderwhite1.webp",
      "/exoticcar/lamborghini/hurucanevospyderwhite/huracanevospyderwhite2.webp",
      "/exoticcar/lamborghini/hurucanevospyderwhite/huracanevospyderwhite3.webp",
      "/exoticcar/lamborghini/hurucanevospyderwhite/huracanevospyderwhite4.webp",
      "/exoticcar/lamborghini/hurucanevospyderwhite/huracanevospyderwhite5.webp",
    ],
  },
  {
    id: "lamborghini-huracan-evo-spyder-yellow",
    name: "Lamborghini Huracan Evo Spyder (Yellow)",
    section: "daily",
    group: "Lamborghini",
    priceLine: "$1399 / day",
    pricing: "daily",
    description:
      "Combine the Evo's sharper dynamics with open-top drama. The Huracan Evo Spyder turns the Miami backdrop into a moving stage with its quick-folding roof and vivid engine note. Aerodynamic refinements and strong brakes deliver composed, exciting performance. The cabin features supportive seats, upscale finishes, and straightforward controls. With the roof up, you get coupe-like calm; with the roof down, you enjoy full skyline views and sea air. Choose the Evo Spyder when you want maximum theater with everyday usability. It's a standout for waterfront cruises, photo shoots, and special nights out.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Convertible" },
      { label: "Color", value: "Yellow" },
      { label: "Brand", value: "Lamborghini" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/huracanevospyderyellow/huracanevospyderyellow1.webp",
      "/exoticcar/lamborghini/huracanevospyderyellow/huracanevospyderyellow2.webp",
      "/exoticcar/lamborghini/huracanevospyderyellow/huracanevospyderyellow3.webp",
      "/exoticcar/lamborghini/huracanevospyderyellow/huracanevospyderyellow4.webp",
    ],
  },
  {
    id: "lamborghini-huracan-evo-blue",
    name: "Lamborghini Huracan Evo (Blue)",
    section: "daily",
    group: "Lamborghini",
    priceLine: "$1299 / day",
    pricing: "daily",
    description:
      "The Huracan Evo heightens the Huracan formula with sharpened aerodynamics and chassis tuning. It looks aggressive and focused, turning heads in hotel entrances and valet lines. Response to steering and throttle is immediate, making every drive feel precise. Inside, expect a driver-centric layout with premium materials and clear digital displays. The suspension blends control and comfort, keeping the car stable over Miami streets while remaining ready for dynamic roads. Rent the Huracan Evo if you want a modern, honed supercar experience. It's tailored for guests who value performance, design, and a confident arrival.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Coupe" },
      { label: "Color", value: "Blue" },
      { label: "Brand", value: "Lamborghini" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/huracanevoblue/huracanevoblue1.webp",
      "/exoticcar/lamborghini/huracanevoblue/huracanevoblue2.webp",
      "/exoticcar/lamborghini/huracanevoblue/huracanevoblue3.webp",
      "/exoticcar/lamborghini/huracanevoblue/huracanevoblue4.webp",
      "/exoticcar/lamborghini/huracanevoblue/huracanevoblue5.webp",
    ],
  },
  {
    id: "lamborghini-huracan-spyder-red",
    name: "Lamborghini Huracan Spyder (red)",
    section: "daily",
    group: "Lamborghini",
    priceLine: "$1199 / day",
    pricing: "daily",
    description:
      "Rent the Huracan Spyder to pair open-air freedom with supercar performance. The power roof operates quickly, turning Miami's skyline and sea breeze into part of the experience. The V10's note intensifies with the top down, delivering sound and sensation in equal measure. Handling is precise, with quick steering and confident braking that suit both city drives and scenic causeways. Inside, the Spyder offers premium trim, modern tech, and supportive seats for comfortable top-down cruising. For guests who want immersive views and unmistakable style, the Huracan Spyder delivers. It's the perfect choice for golden-hour photos and unforgettable coastal drives.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Convertible" },
      { label: "Color", value: "Red" },
      { label: "Brand", value: "Lamborghini" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/huracanspyderred/huracanspyderred1.webp",
      "/exoticcar/lamborghini/huracanspyderred/huracanspyderred2.webp",
      "/exoticcar/lamborghini/huracanspyderred/huracanspyderred3.webp",
      "/exoticcar/lamborghini/huracanspyderred/huracanspyderred4.webp",
    ],
  },
  {
    id: "lamborghini-huracan-white",
    name: "Lamborghini Huracan (White)",
    section: "daily",
    group: "Lamborghini",
    priceLine: "$1099 / day",
    pricing: "daily",
    description:
      "A Lamborghini Huracan rental transforms any Miami itinerary. The low, wedge-shaped profile, dramatic angles, and signature V10 soundtrack create instant theater wherever you arrive. Lightning-fast shifts and communicative steering keep the car responsive and engaging. The cockpit is driver-focused with premium materials, supportive seating, and clear infotainment. Ride quality remains composed over city pavement while the chassis stays alert for spirited driving. It is equal parts showpiece and precision instrument. Choose the Huracan to make statement entrances and enjoy pure supercar feel. It is ideal for luxury dinners, hotel arrivals, and photo-ready cruises along the waterfront.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Coupe" },
      { label: "Color", value: "White" },
      { label: "Brand", value: "Lamborghini" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: ["/exoticcar/lamborghini/huracanwhite/huracanwhite.webp"],
  },
  {
    id: "lamborghini-evo-spyder-grey",
    name: "Lamborghini Huracan Evo Spyder (Grey)",
    section: "daily",
    group: "Lamborghini",
    priceLine: "$1099 / day",
    pricing: "daily",
    description:
      "The Lamborghini Huracán EVO Spyder RWD is an exhilarating open-top supercar that combines the thrill of rear-wheel drive with the visceral experience of top-down driving. Powered by a roaring 5.2-liter V10 engine, it delivers breathtaking performance and sharp handling. The distinctive design features aggressive lines, sleek aerodynamics, and signature Lamborghini styling cues. Inside, the cabin is luxuriously appointed with a mix of high-end materials and cutting-edge technology to ensure both comfort and connectivity. With its retractable soft top, the Huracán EVO Spyder RWD provides an immersive driving experience, letting you fully enjoy the sound and sensation of the powerful V10 engine.",
    specs: [
      { label: "Terms", value: "100 free miles/day | $4/extra mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "610 hp" },
      { label: "Seats", value: "2" },
      { label: "0–60 mph", value: "3.3 sec" },
      { label: "MSRP", value: "$285k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey1.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey2.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey3.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey4.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey5.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey6.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey7.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey8.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey9.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey10.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey11.jpg",
      "/exoticcar/lamborghini/huracanevospydergrey/huracanevospydergrey12.jpg",
    ],
  },
  {
    id: "lamborghini-temerario",
    name: "Lamborghini Temerario",
    section: "daily",
    group: "Lamborghini",
    priceLine: "$1599 / day",
    pricing: "daily",
    featured: true,
    description:
      "Step into the next generation of performance with the Lamborghini Temerario, the revolutionary hybrid supercar replacing the iconic Huracán. Designed for pure adrenaline and cutting-edge innovation, the Temerario blends Lamborghini's legendary design with electrified power to create an unforgettable driving experience. Under the hood, the Temerario features a twin-turbocharged 4.0-liter V8 paired with three electric motors, producing over 900 horsepower. This advanced hybrid system launches the car from 0–60 mph in about 2.7 seconds and reaches a top speed of over 210 mph, delivering explosive acceleration and razor-sharp handling. The engine revs to an astonishing 10,000 RPM, creating a sound and sensation unlike any other hybrid supercar. Combined with all-wheel drive, torque vectoring, and lightning-fast dual-clutch transmission, the Temerario offers unmatched control whether cruising the city or unleashing its power on open roads.",
    specs: [
      { label: "Terms", value: "75 free miles/day | $14 extra per mile" },
      { label: "Security deposit", value: "$500–$1000" },
      {
        label: "Minimum days",
        value: "Weekend (F–S): 2 days · Weekdays (M–T): 1 day",
      },
      { label: "Engine", value: "920 hp" },
      { label: "Seats", value: "2" },
      { label: "0–60 mph", value: "2.5 sec" },
      { label: "MSRP", value: "$475k" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario1.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario2.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario3.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario4.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario5.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario6.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario7.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario8.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario9.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario10.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario11.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario12.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario13.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario14.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario15.jpg",
      "/exoticcar/lamborghini/lamborghinitemerario/lamborghinitemerario16.jpg",
    ],
  },

  {
    id: "ferrari-purosangue-suv",
    name: "Ferrari Purosangue (SUV)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Ferrari",
    priceLine: "$2095 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "Experience luxury with this Ferrari Purosangue in Miami—the marque’s four-door, four-wheel-drive expression of Ferrari performance and design. Perfect for an unforgettable stay, it pairs world-class amenities with meticulous presentation. Blackline coordinates your rental end to end—handover, timing, and optional routing—so every detail meets your expectations.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Seats", value: "5" },
      { label: "Style", value: "SUV" },
      { label: "Segment", value: "Luxury" },
      { label: "Brand", value: "Ferrari" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/ferrari/purosangue/purosangue1.png",
      "/exoticcar/ferrari/purosangue/purosangue2.png",
      "/exoticcar/ferrari/purosangue/purosangue3.png",
    ],
  },
  {
    id: "lamborghini-urus-red",
    name: "Lamborghini Urus (Red)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Lamborghini",
    priceLine: "$995 / day",
    chauffeurPriceLine: "XXX / hr",
    pricing: "daily",
    description:
      "Experience luxury with this Lamborghini Urus in striking red, available in Miami. Perfect for an unforgettable stay, it pairs super-SUV presence with world-class amenities and meticulous presentation. Blackline coordinates your rental end to end—handover, timing, and optional routing—so every detail meets your expectations.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "XXX / hr" },
      { label: "Seats", value: "5" },
      { label: "Style", value: "SUV" },
      { label: "Segment", value: "Luxury" },
      { label: "Color", value: "Red" },
      { label: "Brand", value: "Lamborghini" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/urusred/urusred1.jpg",
      "/exoticcar/lamborghini/urusred/urusred2.jpg",
      "/exoticcar/lamborghini/urusred/urusred3.jpg",
      "/exoticcar/lamborghini/urusred/urusred4.jpg",
      "/exoticcar/lamborghini/urusred/urusred5.jpg",
      "/exoticcar/lamborghini/urusred/urusred6.png",
    ],
  },
  {
    id: "lamborghini-urus-widebody",
    name: "Lamborghini Urus WideBody",
    section: "daily",
    group: "Lamborghini",
    dualRentalOnCard: true,
    priceLine: "$950 / day",
    chauffeurPriceLine: "$200–$250 / hr — driver included",
    pricing: "daily",
    description:
      "Experience luxury with this Lamborghini Urus Widebody in Miami—bold widebody presence, bespoke cabin details, and the versatility of a super-SUV. Blackline coordinates your booking from inquiry through return: self-drive rental (license and insurance required) or optional chauffeur service, timed with the rest of your stay.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$200–$250/hr — driver included" },
      { label: "Seats", value: "3" },
      { label: "Style", value: "SUV" },
      { label: "Segment", value: "Luxury" },
      { label: "Trim", value: "Widebody" },
      { label: "Brand", value: "Lamborghini" },
    ],
    highlights: [
      "Wide body kit exterior",
      "Black & yellow hexagon-stitched leather sport seats",
      "Yellow leather-wrapped steering wheel with Italian flag detail",
      "Lamborghini-branded rear headrest entertainment screen",
      "Drive mode selector console (Strada, Sport, Corsa, and more)",
      "Digital instrument cluster",
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/uruswidebody/uruswidebody1.png",
      "/exoticcar/lamborghini/uruswidebody/uruswidebody2.jpg",
      "/exoticcar/lamborghini/uruswidebody/uruswidebody3.jpg",
      "/exoticcar/lamborghini/uruswidebody/uruswidebody4.jpg",
      "/exoticcar/lamborghini/uruswidebody/uruswidebody5.jpg",
      "/exoticcar/lamborghini/uruswidebody/uruswidebody6.jpg",
      "/exoticcar/lamborghini/uruswidebody/uruswidebody7.jpg",
    ],
  },
  {
    id: "lamborghini-huracan-evo-spyder-orange",
    name: "Lamborghini Huracan Evo Spyder (Orange)",
    section: "daily",
    group: "Lamborghini",
    priceLine: "$1095 / day",
    pricing: "daily",
    description:
      "Experience luxury with this Lamborghini Huracán Evo Spyder in Miami—open-air V10 drama, sharp lines, and unmistakable presence in orange. Perfect for an unforgettable stay, it pairs world-class amenities with meticulous presentation. Blackline coordinates your rental end to end—handover, timing, and optional routing—so every detail meets your expectations.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Convertible" },
      { label: "Segment", value: "Luxury" },
      { label: "Color", value: "Orange" },
      { label: "Brand", value: "Lamborghini" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/evospyderorange/evospyderorange1.jpeg",
    ],
  },
  {
    id: "lamborghini-huracan-evo-spyder-stage-2",
    name: "Lamborghini Huracan Evo Spyder (Stage 2)",
    section: "daily",
    group: "Lamborghini",
    priceLine: "$1095 / day",
    pricing: "daily",
    description:
      "Experience luxury with this Lamborghini Huracán Evo Spyder Stage 2 in Miami—tuned presence, open-air V10 character, and focused performance cues. Perfect for an unforgettable stay, it pairs world-class amenities with meticulous presentation. Blackline coordinates your rental end to end—handover, timing, and optional routing—so every detail meets your expectations.",
    specs: [
      { label: "Seats", value: "2" },
      { label: "Style", value: "Convertible" },
      { label: "Segment", value: "Luxury" },
      { label: "Build", value: "Stage 2" },
      { label: "Brand", value: "Lamborghini" },
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/lamborghini/evospyderstage2/evospyderstage2-1.png",
      "/exoticcar/lamborghini/evospyderstage2/evospyderstage2-2.png",
    ],
  },
  {
    id: "mercedes-maybach-gls-600-unit-c",
    name: "Mercedes Maybach GLS 600 (Unit C)",
    section: "daily",
    dualRentalOnCard: true,
    group: "Mercedes",
    priceLine: "$800 / day",
    chauffeurPriceLine: "$175 / hr",
    pricing: "daily",
    description:
      "Experience luxury with this Mercedes-Maybach GLS 600 in Miami—Unit C delivers first-class rear accommodation, refined road presence, and meticulous cabin finish. Perfect for an unforgettable stay, it pairs world-class amenities with attention to detail. Blackline coordinates your booking end to end—self-drive rental (license and insurance required) or optional chauffeur service—timed with the rest of your itinerary.",
    specs: [
      { label: "Self-drive", value: "License & insurance required" },
      { label: "Chauffeur", value: "$175 / hr" },
      { label: "Seats", value: "5" },
      { label: "Style", value: "SUV" },
      { label: "Segment", value: "Luxury" },
      { label: "Unit", value: "C" },
      { label: "Brand", value: "Mercedes-Maybach" },
    ],
    highlights: [
      "Maybach-branded interior sill plates",
      "Individual rear captain seats with integrated touchscreen controls",
      "Quilted black leather throughout",
      "Rear privacy shades",
      "Dual rear-seat tablet/control panels",
    ],
    requirements: [
      "Valid Drivers License (We Accept Foreigners)",
      "Debit or Credit Card",
      "$1000 Deposit",
    ],
    galleryImages: [
      "/exoticcar/mercedes/gls600-c/gls600-c-1.png",
      "/exoticcar/mercedes/gls600-c/gls600-c-2.jpg",
      "/exoticcar/mercedes/gls600-c/gls600-c-3.jpg",
      "/exoticcar/mercedes/gls600-c/gls600-c-4.jpg",
      "/exoticcar/mercedes/gls600-c/gls600-c-5.jpg",
      "/exoticcar/mercedes/gls600-c/gls600-c-6.jpg",
    ],
  },
];

export const ALL_EXOTIC_CARS: ExoticCar[] = [
  ...EXOTIC_CARS_HOURLY_GROUPS.flatMap((g) => g.cars),
  ...EXOTIC_CARS_DAILY,
];
