import { CHALLENGER_300_GALLERY_PATHS } from "./challenger-300-gallery";
import { CHALLENGER_350_GALLERY_PATHS } from "./challenger-350-gallery";
import { CHALLENGER_605_GALLERY_PATHS } from "./challenger-605-gallery";
import { EMBRAER_LEGACY_600_GALLERY_PATHS } from "./embraer-legacy-600-gallery";
import { EMBRAER_LEGACY_650_GALLERY_PATHS } from "./embraer-legacy-650-gallery";
import { FALCON_2000_GALLERY_PATHS } from "./falcon-2000-gallery";
import { FALCON_900EX_EASY_GALLERY_PATHS } from "./falcon-900ex-easy-gallery";
import { GLOBAL_EXPRESS_GALLERY_PATHS } from "./global-express-gallery";
import { GLOBAL_EXPRESS_XRS_GALLERY_PATHS } from "./global-express-xrs-gallery";
import { GULFSTREAM_G400_GALLERY_PATHS } from "./gulfstream-g400-gallery";
import { GULFSTREAM_G450_GALLERY_PATHS } from "./gulfstream-g450-gallery";
import { GULFSTREAM_G550_GALLERY_PATHS } from "./gulfstream-g550-gallery";
import { GULFSTREAM_GIV_GALLERY_PATHS } from "./gulfstream-giv-gallery";
import { GULFSTREAM_GIV_SP_GALLERY_PATHS } from "./gulfstream-giv-sp-gallery";
import { GULFSTREAM_G280_GALLERY_PATHS } from "./gulfstream-g280-gallery";
import { LEARJET_60_GALLERY_PATHS } from "./learjet-60-gallery";

export type PrivateJetCategory = "ultra-long-range" | "super-mid-size" | "mid-size";

export type PrivateJet = {
  id: string;
  name: string;
  category: PrivateJetCategory;
  categoryLabel: string;
  passengers: string;
  beds: number;
  range: string;
  cruisingSpeed: string;
  baggage: string;
  interiorWidth: string;
  interiorHeight: string;
  overview: string;
  amenities: readonly string[];
  /** Local paths under `public/privatejets/` — first is catalog card + dialog hero cover. */
  galleryPaths?: readonly string[];
};

/** Grouped for display — order matches the charter lineup provided. */
export const PRIVATE_JETS: PrivateJet[] = [
  {
    id: "gulfstream-giv-sp",
    name: "Gulfstream GIV-SP",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 12",
    beds: 5,
    range: "4,200 miles",
    cruisingSpeed: "850 km/h",
    baggage: "169 cubic feet",
    interiorWidth: "7.3 feet",
    interiorHeight: "6.1 feet",
    overview:
      "The Gulfstream GIV-SP is a proven heavy jet with intercontinental reach and a spacious cabin that comfortably seats 12 passengers. With sleeping accommodations for five, it's an ideal choice for overnight transcontinental and transatlantic flights.",
    amenities: [
      "Fully enclosed lavatory",
      "Full galley with catering",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Berthing seats for sleeping",
      "Executive leather seating",
      "Fold-out work tables",
      "Entertainment system",
    ],
    galleryPaths: GULFSTREAM_GIV_SP_GALLERY_PATHS,
  },
  {
    id: "gulfstream-g280",
    name: "Gulfstream G280",
    category: "super-mid-size",
    categoryLabel: "Super mid size",
    passengers: "Up to 9",
    beds: 0,
    range: "3,600 miles",
    cruisingSpeed: "900 km/h",
    baggage: "154 cubic feet",
    interiorWidth: "6.11 feet",
    interiorHeight: "6.1 feet",
    overview:
      "The Gulfstream G280 delivers super-midsize performance with a wide, flat-floor cabin and impressive 3,600-mile range. It's the perfect aircraft for coast-to-coast flights with up to 9 passengers in refined comfort.",
    amenities: [
      "Fully enclosed lavatory",
      "Full refreshment center",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "Wi-Fi connectivity",
      "Stand-up cabin",
      "Executive leather seating",
      "Fold-out work tables",
    ],
    galleryPaths: GULFSTREAM_G280_GALLERY_PATHS,
  },
  {
    id: "falcon-900ex-easy",
    name: "Falcon 900EX EASy",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 14",
    beds: 5,
    range: "4,300 miles",
    cruisingSpeed: "545 mph",
    baggage: "127 cubic feet",
    interiorWidth: "7.7 feet",
    interiorHeight: "6.2 feet",
    overview:
      "The Falcon 900EX EASy is a tri-engine ultra-long-range jet offering exceptional safety, performance, and versatility. With seating for 14 and sleeping for 5, it handles intercontinental missions with ease while accessing shorter runways other large-cabin jets cannot.",
    amenities: [
      "Multiple cabin zones",
      "Full galley with catering",
      "Forward & aft lavatories",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Dedicated sleeping quarters",
      "Executive leather seating",
      "Conference/dining area",
      "Entertainment system",
      "Crew rest area",
    ],
    galleryPaths: FALCON_900EX_EASY_GALLERY_PATHS,
  },
  {
    id: "global-express",
    name: "Global Express",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 12",
    beds: 5,
    range: "6,226 miles",
    cruisingSpeed: "950 km/h",
    baggage: "185 cubic feet",
    interiorWidth: "8.17 feet",
    interiorHeight: "6.25 feet",
    overview:
      "The Bombardier Global Express is a flagship ultra-long-range jet with a wide-body cabin spanning over 8 feet across. Capable of flying 6,226 miles nonstop, it connects continents in unmatched comfort for up to 12 passengers.",
    amenities: [
      "Multiple cabin zones",
      "Full galley with catering",
      "Forward & aft lavatories",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Dedicated sleeping quarters",
      "Executive leather seating",
      "Conference/dining area",
      "Entertainment system",
      "Crew rest area",
    ],
    galleryPaths: GLOBAL_EXPRESS_GALLERY_PATHS,
  },
  {
    id: "challenger-605",
    name: "Challenger 605",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 12",
    beds: 4,
    range: "4,000 miles",
    cruisingSpeed: "870 km/h",
    baggage: "115 cubic feet",
    interiorWidth: "8.2 feet",
    interiorHeight: "6.1 feet",
    overview:
      "The Challenger 605 features one of the widest cabins in its class at 8.2 feet, paired with a 4,000-mile range. With seating for 12 and beds for 4, it delivers heavy-jet luxury and versatility for transcontinental travel.",
    amenities: [
      "Fully enclosed lavatory",
      "Full galley with catering",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Berthing seats for sleeping",
      "Executive leather seating",
      "Fold-out work tables",
      "Entertainment system",
    ],
    galleryPaths: CHALLENGER_605_GALLERY_PATHS,
  },
  {
    id: "global-express-xrs",
    name: "Global Express XRS",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 15",
    beds: 5,
    range: "6,390 miles",
    cruisingSpeed: "950 km/h",
    baggage: "195 cubic feet",
    interiorWidth: "8.17 feet",
    interiorHeight: "6.27 feet",
    overview:
      "The Global Express XRS extends the legendary Global Express platform with enhanced range of 6,390 miles and a refined cabin for up to 15 passengers. It's built for nonstop intercontinental missions in world-class comfort.",
    amenities: [
      "Multiple cabin zones",
      "Full galley with catering",
      "Forward & aft lavatories",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Dedicated sleeping quarters",
      "Executive leather seating",
      "Conference/dining area",
      "Entertainment system",
      "Crew rest area",
    ],
    galleryPaths: GLOBAL_EXPRESS_XRS_GALLERY_PATHS,
  },
  {
    id: "gulfstream-g400",
    name: "Gulfstream G400",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 13",
    beds: 5,
    range: "4,200 miles",
    cruisingSpeed: "539 km/h",
    baggage: "169 cubic feet",
    interiorWidth: "7.3 feet",
    interiorHeight: "6.1 feet",
    overview:
      "The Gulfstream G400 brings heavy-jet comfort and range in a refined package, seating 13 passengers with sleeping accommodations for 5. It's an excellent choice for cross-country and Caribbean flights.",
    amenities: [
      "Fully enclosed lavatory",
      "Full galley with catering",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Berthing seats for sleeping",
      "Executive leather seating",
      "Fold-out work tables",
      "Entertainment system",
    ],
    galleryPaths: GULFSTREAM_G400_GALLERY_PATHS,
  },
  {
    id: "learjet-60",
    name: "Learjet 60",
    category: "mid-size",
    categoryLabel: "Mid size",
    passengers: "Up to 7",
    beds: 0,
    range: "2,400 miles",
    cruisingSpeed: "839 km/h",
    baggage: "59 cubic feet",
    interiorWidth: "5 ft 11 in",
    interiorHeight: "5 ft 9 in",
    overview:
      "The Learjet 60 is a proven midsize performer known for its speed and efficiency. Seating 7 passengers with a 2,400-mile range, it's ideal for regional business travel and quick domestic hops.",
    amenities: [
      "Fully enclosed lavatory",
      "Refreshment center",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "Wi-Fi available",
      "Executive leather seating",
    ],
    galleryPaths: LEARJET_60_GALLERY_PATHS,
  },
  {
    id: "embraer-legacy-600",
    name: "Embraer Legacy 600",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 13",
    beds: 5,
    range: "3,400 miles",
    cruisingSpeed: "834 km/h",
    baggage: "286 cubic feet",
    interiorWidth: "6.9 feet",
    interiorHeight: "6.76 feet",
    overview:
      "The Embraer Legacy 600 offers an exceptionally spacious cabin with the largest baggage compartment in its class at 286 cubic feet. Seating 13 with beds for 5, it's perfect for travelers who need to bring it all.",
    amenities: [
      "Fully enclosed lavatory",
      "Full galley with catering",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Berthing seats for sleeping",
      "Executive leather seating",
      "Fold-out work tables",
      "Entertainment system",
    ],
    galleryPaths: EMBRAER_LEGACY_600_GALLERY_PATHS,
  },
  {
    id: "challenger-350",
    name: "Challenger 350",
    category: "super-mid-size",
    categoryLabel: "Super mid size",
    passengers: "Up to 9",
    beds: 0,
    range: "3,300 miles",
    cruisingSpeed: "891 km/h",
    baggage: "106 cubic feet",
    interiorWidth: "7.2 feet",
    interiorHeight: "6.2 feet",
    overview:
      "The Challenger 350 is a best-in-class super-midsize jet combining a wide cabin, smooth ride, and 3,300-mile range. With seating for 9, it's the go-to choice for coast-to-coast business travel.",
    amenities: [
      "Fully enclosed lavatory",
      "Full refreshment center",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "Wi-Fi connectivity",
      "Stand-up cabin",
      "Executive leather seating",
      "Fold-out work tables",
    ],
    galleryPaths: CHALLENGER_350_GALLERY_PATHS,
  },
  {
    id: "gulfstream-g550",
    name: "Gulfstream G550",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 16",
    beds: 6,
    range: "6,750 miles",
    cruisingSpeed: "941 km/h",
    baggage: "226 cubic feet",
    interiorWidth: "7.4 feet",
    interiorHeight: "6.2 feet",
    overview:
      "The Gulfstream G550 is a legendary ultra-long-range jet with a 6,750-mile range and seating for up to 16 passengers. With 6 sleeping berths and a spacious cabin, it sets the standard for intercontinental private travel.",
    amenities: [
      "Multiple cabin zones",
      "Full galley with catering",
      "Forward & aft lavatories",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Dedicated sleeping quarters",
      "Executive leather seating",
      "Conference/dining area",
      "Entertainment system",
      "Crew rest area",
    ],
    galleryPaths: GULFSTREAM_G550_GALLERY_PATHS,
  },
  {
    id: "gulfstream-g450",
    name: "Gulfstream G450",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 13",
    beds: 5,
    range: "4,200 miles",
    cruisingSpeed: "539 km/h",
    baggage: "169 cubic feet",
    interiorWidth: "7.3 feet",
    interiorHeight: "6.1 feet",
    overview:
      "The Gulfstream G450 combines heavy-jet cabin space with a 4,200-mile range, comfortably seating 13 with beds for 5. It delivers the quintessential Gulfstream experience for transcontinental and international flights.",
    amenities: [
      "Fully enclosed lavatory",
      "Full galley with catering",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Berthing seats for sleeping",
      "Executive leather seating",
      "Fold-out work tables",
      "Entertainment system",
    ],
    galleryPaths: GULFSTREAM_G450_GALLERY_PATHS,
  },
  {
    id: "gulfstream-giv",
    name: "Gulfstream GIV",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 16",
    beds: 5,
    range: "4,200 miles",
    cruisingSpeed: "850 km/h",
    baggage: "169 cubic feet",
    interiorWidth: "7.3 feet",
    interiorHeight: "6.1 feet",
    overview:
      "The Gulfstream GIV is a time-tested heavy jet with seating for up to 16 passengers and a proven 4,200-mile range. It offers generous cabin space and sleeping accommodations for coast-to-coast and transatlantic missions.",
    amenities: [
      "Fully enclosed lavatory",
      "Full galley with catering",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Berthing seats for sleeping",
      "Executive leather seating",
      "Fold-out work tables",
      "Entertainment system",
    ],
    galleryPaths: GULFSTREAM_GIV_GALLERY_PATHS,
  },
  {
    id: "challenger-300",
    name: "Challenger 300",
    category: "super-mid-size",
    categoryLabel: "Super mid size",
    passengers: "Up to 8",
    beds: 0,
    range: "3,300 miles",
    cruisingSpeed: "891 km/h",
    baggage: "106 cubic feet",
    interiorWidth: "7.2 feet",
    interiorHeight: "6.1 feet",
    overview:
      "The Challenger 300 is a super-midsize jet with a wide flat-floor cabin and impressive 3,300-mile range. Seating 8 passengers in comfort, it excels at coast-to-coast and Caribbean routes.",
    amenities: [
      "Fully enclosed lavatory",
      "Full refreshment center",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "Wi-Fi connectivity",
      "Stand-up cabin",
      "Executive leather seating",
      "Fold-out work tables",
    ],
    galleryPaths: CHALLENGER_300_GALLERY_PATHS,
  },
  {
    id: "falcon-2000",
    name: "Dassault Falcon 2000",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 10",
    beds: 4,
    range: "3,200 miles",
    cruisingSpeed: "880 km/h",
    baggage: "134 cubic feet",
    interiorWidth: "7.7 feet",
    interiorHeight: "6.2 feet",
    overview:
      "The Dassault Falcon 2000 is a wide-body heavy jet offering a spacious 7.7-foot-wide cabin and 3,200-mile range. With seating for 10 and beds for 4, it delivers French-engineered luxury for domestic and Caribbean travel.",
    amenities: [
      "Fully enclosed lavatory",
      "Full galley with catering",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Berthing seats for sleeping",
      "Executive leather seating",
      "Fold-out work tables",
      "Entertainment system",
    ],
    galleryPaths: FALCON_2000_GALLERY_PATHS,
  },
  {
    id: "embraer-legacy-650",
    name: "Embraer Legacy 650",
    category: "ultra-long-range",
    categoryLabel: "Ultra long range",
    passengers: "Up to 13",
    beds: 5,
    range: "3,900 miles",
    cruisingSpeed: "829 km/h",
    baggage: "286 cubic feet",
    interiorWidth: "6.92 feet",
    interiorHeight: "6.00 feet",
    overview:
      "The Embraer Legacy 650 builds on the Legacy 600 with extended 3,900-mile range and the same best-in-class 286 cubic feet of baggage capacity. It seats 13 with 5 beds, making it ideal for long trips with heavy luggage.",
    amenities: [
      "Fully enclosed lavatory",
      "Full galley with catering",
      "Climate-controlled cabin",
      "Power outlets & USB charging",
      "High-speed Wi-Fi",
      "Stand-up cabin",
      "Berthing seats for sleeping",
      "Executive leather seating",
      "Fold-out work tables",
      "Entertainment system",
    ],
    galleryPaths: EMBRAER_LEGACY_650_GALLERY_PATHS,
  },
];

export const PRIVATE_JET_CATEGORY_FILTERS: {
  id: "all" | PrivateJetCategory;
  label: string;
}[] = [
  { id: "all", label: "All aircraft" },
  { id: "ultra-long-range", label: "Ultra long range" },
  { id: "super-mid-size", label: "Super mid size" },
  { id: "mid-size", label: "Mid size" },
];
