export type VillaFact = {
  label: string;
  value: string;
};

/** Miami-area neighborhoods for directory filtering (order = filter chip order). */
export const VILLA_NEIGHBORHOODS = [
  "Golden Beach",
  "Miami Beach",
  "Venetian Islands",
  "Miami Shores",
  "Coral Gables",
  "Hollywood",
  "Upper East Side",
  "North Miami",
  "Key Largo",
  "Aventura",
  "Hallandale Beach",
] as const;

export type VillaNeighborhood = (typeof VILLA_NEIGHBORHOODS)[number];

export type Villa = {
  id: string;
  name: string;
  subtitle: string;
  /** Miami area — filters the catalog. */
  neighborhood: VillaNeighborhood;
  /** One line on cards — beds, location, or scale. */
  cardTagline: string;
  /** Short lead paragraph in the detail panel. */
  lede: string;
  /** Longer description body. */
  description: string;
  facts: readonly VillaFact[];
  highlights: readonly string[];
  /** VIP / transport / arrival experience in polished copy. */
  vipNote?: string;
  inclusions?: readonly string[];
  policyNotes?: readonly string[];
  /** Gallery image URLs — local `/…` paths or absolute URLs. */
  galleryImages: readonly string[];
};

/**
 * Miami-area villa stays. Add entries here as you receive names, copy, and photos.
 */
export const VILLAS: readonly Villa[] = [
  {
    id: "aria",
    name: "Aria",
    subtitle: "North Miami · waterfront",
    neighborhood: "North Miami",
    cardTagline: "6 bed · 6.5 bath · 10,000 sq ft",
    lede:
      "Villa Aria is a newly renovated luxury resort-style waterfront home in North Miami with over 10,000 square feet of contemporary living, wide-bay views, and a resort-style pool deck.",
    description:
      "Villa Aria is a newly renovated luxury resort-style waterfront villa, offering over 10,000 square feet of modern contemporary living space. Villa Aria is the definition of Miami grandeur, featuring six bedrooms and six and a half bathrooms plus an office, den, gym, and sauna. Villa Aria’s eye-catching yet functional design offers ample open spaces and wall-to-wall sliding glass doors that completely open, creating the ultimate indoor–outdoor experience. High-end finishes in natural tones and splendid scenery of Miami Beach. Embrace the living areas and oasis-like pool deck with breathtaking wide-bay views. Inside, a state-of-the-art kitchen sits between the living, formal dining, and family room — all opening to the pool deck featuring a spa and patio with a summer kitchen and a Naples-style outdoor pizza oven. The exquisite master suite includes custom-built closets and a luxe bath — brilliantly designed for seamless connection between the indoor and outdoor.",
    facts: [
      { label: "Location", value: "North Miami" },
      { label: "Property size", value: "10,000 sq ft" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "6.5" },
      { label: "Max guests", value: "12" },
      {
        label: "Check-in & check-out",
        value: "Confirmed when you book",
      },
    ],
    highlights: [
      "Over 10,000 sq ft with six bedrooms, office, den, gym, and sauna",
      "Wall-to-wall sliding glass for full indoor–outdoor flow; summer kitchen and Naples-style outdoor pizza oven",
      "Waterfront pool deck, spa, and wide-bay views toward Miami Beach",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
    ],
    policyNotes: [
      "Maximum guests: 12.",
      "Children, pets, events, and smoking are not permitted.",
    ],
    galleryImages: [
      "/stays/aria/aria1.webp",
      "/stays/aria/aria2.jpg",
      "/stays/aria/aria3.jpg",
      "/stays/aria/aria4.jpg",
      "/stays/aria/aria5.jpg",
      "/stays/aria/aria6.jpg",
      "/stays/aria/aria7.jpg",
      "/stays/aria/aria8.jpg",
      "/stays/aria/aria9.jpg",
      "/stays/aria/aria10.jpg",
    ],
  },
  {
    id: "astro",
    name: "Astro",
    subtitle: "Hallandale Beach · Golden Isles",
    neighborhood: "Hallandale Beach",
    cardTagline: "5 bed · 3.5 bath · 3,700 sq ft",
    lede:
      "A newly renovated waterfront home in the gated Golden Isles community in Hallandale Beach — 85 ft of water frontage, boater-friendly setup, and bright indoor–outdoor entertaining.",
    description:
      "This newly renovated waterfront oasis in the exclusive gated community of Golden Isles in Hallandale Beach, just north of Miami Beach, Florida, offers paradise living and entertaining spaces to satisfy a true boater’s dream. Sitting upon 85 ft of prime water frontage, the home boasts five bedrooms, three and a half bathrooms, about 3,700 square feet, and exceptional natural light throughout. Interior finishes, master chef’s kitchen, a built-in bar, an outdoor kitchen and barbecue area, and a private sauna make this home the perfect all-inclusive vacation rental villa retreat.",
    facts: [
      { label: "Location", value: "Hallandale Beach · Golden Isles" },
      { label: "Property size", value: "3,700 sq ft" },
      { label: "Bedrooms", value: "5" },
      { label: "Bathrooms", value: "3.5" },
      { label: "Max guests", value: "10" },
      { label: "Check-in", value: "After 3:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "85 ft of prime waterfront in a gated community",
      "Chef’s kitchen, built-in bar, outdoor kitchen & BBQ, private sauna",
      "Putting green, private parking, and spaces tailored for boaters",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
      "Putting green",
      "Private parking",
    ],
    policyNotes: [
      "Maximum guests: 10.",
      "Children and pets allowed. Events allowed. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/astro/astro1.jpg",
      "/stays/astro/astro2.jpg",
      "/stays/astro/astro3.jpg",
      "/stays/astro/astro4.jpg",
      "/stays/astro/astro5.jpg",
      "/stays/astro/astro6.jpg",
      "/stays/astro/astro7.jpg",
      "/stays/astro/astro8.jpg",
      "/stays/astro/astro9.jpg",
      "/stays/astro/astro10.jpg",
      "/stays/astro/astro11.jpg",
      "/stays/astro/astro12.jpg",
      "/stays/astro/astro13.jpg",
      "/stays/astro/astro14.jpg",
      "/stays/astro/astro15.jpg",
      "/stays/astro/astro16.jpg",
      "/stays/astro/astro17.jpg",
      "/stays/astro/astro18.jpg",
      "/stays/astro/astro19.jpg",
      "/stays/astro/astro20.jpg",
      "/stays/astro/astro21.jpg",
      "/stays/astro/astro22.jpg",
      "/stays/astro/astro23.jpg",
      "/stays/astro/astro24.jpg",
      "/stays/astro/astro25.jpg",
      "/stays/astro/astro26.jpg",
      "/stays/astro/astro27.jpg",
      "/stays/astro/astro28.jpg",
      "/stays/astro/astro29.jpg",
      "/stays/astro/astro30.jpg",
      "/stays/astro/astro31.jpg",
    ],
  },
  {
    id: "blockchain-manor",
    name: "Blockchain Manor",
    subtitle: "North Miami · estate",
    neighborhood: "North Miami",
    cardTagline: "6 bed · 4 bath · 4,000 sq ft",
    lede:
      "Private one-acre estate in North Miami with lush gardens, a heated saltwater pool, tiki hut, and full indoor–outdoor entertaining — ideal for large groups who want space and discretion.",
    description:
      "Off the beaten path, this enticing vacation home in Miami is nestled on an oversized one-acre lot. Beautiful gardens provide tons of privacy; a lush tropical oasis sits beside the large heated saltwater pool, featuring palm trees, plumerias, birds of paradise, and orchids. The circular driveway has automatic gate entry. Additional features include a jacuzzi and a large tiki hut. Blockchain Manor features state-of-the-art kitchen appliances both inside and out: Viking custom fridge (to match kitchen cabinets) and an outdoor kitchen decked out with mini fridge and gas grill, perfect for entertaining. Six bedrooms include both an expansive master and junior master upstairs; downstairs are four bedrooms as well as a movie theater that doubles as an additional sleeping space with adjacent full bathroom. A game room containing pool table and foosball also has a flatscreen TV to catch all the games. Sonos speakers throughout the property offer an unmatched entertaining experience.",
    facts: [
      { label: "Location", value: "North Miami" },
      { label: "Property size", value: "4,000 sq ft" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "4" },
      { label: "Max guests", value: "16" },
      { label: "Check-in", value: "After 11:00 am" },
      { label: "Check-out", value: "After 12:00 pm" },
    ],
    highlights: [
      "One-acre grounds with heated saltwater pool, spa, and tiki hut",
      "Theater room, game room, and indoor–outdoor kitchens with premium appliances",
      "Sonos throughout; automatic gated entry and circular drive",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Pool",
      "Outdoor kitchen",
      "Tiki hut",
      "Movie theater",
    ],
    policyNotes: [
      "Maximum guests: 16. Children and pets allowed. Events allowed. No smoking indoors.",
      "Absolutely no parties anywhere in the home or on the premises. Violation fines may exceed $5,000 per occurrence; immediate notice to vacate may be served for party, noise, or police complaints. Fines levied against the landlord by police or the city related to tenant conduct may be billed to the guest; the entire security deposit may be forfeited. Noise violations may incur city fines up to $5,000, deducted from the deposit.",
      "Guests must provide photo ID at check-in. The guest who books must be the person checking in.",
      "No smoking inside the house — $1,000 fine per occurrence from the security deposit. No outside music or DJ equipment; breaking this rule may mean immediate removal and loss of deposit.",
      "Drive slowly and cautiously in the neighborhood — no revving or speeding.",
    ],
    galleryImages: [
      "/stays/blockhainmanor/blockhainmanor1.webp",
      "/stays/blockhainmanor/blockhainmanor2.jpg",
      "/stays/blockhainmanor/blockhainmanor3.jpg",
      "/stays/blockhainmanor/blockhainmanor4.jpg",
      "/stays/blockhainmanor/blockhainmanor5.jpg",
      "/stays/blockhainmanor/blockhainmanor6.jpg",
      "/stays/blockhainmanor/blockhainmanor7.jpg",
      "/stays/blockhainmanor/blockhainmanor8.jpg",
      "/stays/blockhainmanor/blockhainmanor9.jpg",
      "/stays/blockhainmanor/blockhainmanor10.jpg",
      "/stays/blockhainmanor/blockhainmanor11.jpg",
      "/stays/blockhainmanor/blockhainmanor12.jpg",
      "/stays/blockhainmanor/blockhainmanor13.jpg",
      "/stays/blockhainmanor/blockhainmanor14.jpg",
      "/stays/blockhainmanor/blockhainmanor15.jpg",
      "/stays/blockhainmanor/blockhainmanor17.jpg",
      "/stays/blockhainmanor/blockhainmanor18.jpg",
      "/stays/blockhainmanor/blockhainmanor19.jpg",
      "/stays/blockhainmanor/blockhainmanor20.jpg",
      "/stays/blockhainmanor/blockhainmanor21.jpg",
      "/stays/blockhainmanor/blockhainmanor22.jpg",
      "/stays/blockhainmanor/blockhainmanor23.jpg",
      "/stays/blockhainmanor/blockhainmanor24.jpg",
      "/stays/blockhainmanor/blockhainmanor25.jpg",
      "/stays/blockhainmanor/blockhainmanor26.jpg",
      "/stays/blockhainmanor/blockhainmanor27.jpg",
      "/stays/blockhainmanor/blockhainmanor28.jpg",
      "/stays/blockhainmanor/blockhainmanor29.jpg",
      "/stays/blockhainmanor/blockhainmanor30.jpg",
      "/stays/blockhainmanor/blockhainmanor31.jpg",
      "/stays/blockhainmanor/blockhainmanor32.jpg",
      "/stays/blockhainmanor/blockhainmanor33.jpg",
      "/stays/blockhainmanor/blockhainmanor34.jpg",
      "/stays/blockhainmanor/blockhainmanor35.jpg",
      "/stays/blockhainmanor/blockhainmanor36.jpg",
      "/stays/blockhainmanor/blockhainmanor37.jpg",
      "/stays/blockhainmanor/blockhainmanor38.jpg",
      "/stays/blockhainmanor/blockhainmanor39.jpg",
      "/stays/blockhainmanor/blockhainmanor40.jpg",
      "/stays/blockhainmanor/blockhainmanor41.jpg",
      "/stays/blockhainmanor/blockhainmanor42.jpg",
    ],
  },
  {
    id: "divina",
    name: "Divina",
    subtitle: "Venetian Islands · waterfront",
    neighborhood: "Venetian Islands",
    cardTagline: "5 bed · 5.5 bath · 5,662 sq ft",
    lede:
      "2019-built waterfront estate on the Venetian Islands with sunset skyline views, Boffi kitchen and baths, and a rooftop deck over the bay.",
    description:
      "Ultra-high-end luxury waterfront on the Venetian Islands in Miami Beach, facing west and offering incredible Miami skyline and sunset views. Built in 2019, this modern masterpiece features an open-concept floor plan with a family room, glass-enclosed office/bar, dining area, Boffi kitchen, and living room with powered sliding doors. Finishes include exquisite Listone Giordano oak floors, Savant control, 10′ ceilings, Italian frameless doors, and Boffi fixtures and closets. Upstairs: a stunning oversized master suite with luxe bath and large terrace. Outside: heated saltwater pool with spa, Boffi summer kitchen, IPE deck, and new dock/seawall. A ~620 sq ft rooftop deck offers skyline and bay views. Automatic gate, security cameras, three electric car charging stations, and a two-car A/C garage.",
    facts: [
      { label: "Location", value: "Venetian Islands, Miami Beach" },
      { label: "Property size", value: "5,662 sq ft" },
      { label: "Bedrooms", value: "5" },
      { label: "Bathrooms", value: "5.5" },
      { label: "Max guests", value: "12" },
      { label: "Check-in", value: "After 11:00 am" },
      { label: "Check-out", value: "After 4:00 pm" },
    ],
    highlights: [
      "West-facing waterfront with skyline and sunset views",
      "Rooftop deck, heated pool & spa, Boffi summer kitchen, new dock",
      "Savant smart home, EV charging, gated entry with security cameras",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
    ],
    policyNotes: [
      "Maximum guests: 12.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/divina/divina1.webp",
      "/stays/divina/divina2.jpg",
      "/stays/divina/divina3.jpg",
      "/stays/divina/divina4.jpg",
      "/stays/divina/divina5.jpg",
      "/stays/divina/divina6.jpg",
      "/stays/divina/divina7.jpg",
      "/stays/divina/divina8.jpg",
      "/stays/divina/divina9.jpg",
      "/stays/divina/divina10.jpg",
    ],
  },
  {
    id: "emerald",
    name: "Emerald",
    subtitle: "Aventura · estate",
    neighborhood: "Aventura",
    cardTagline: "9 bed · 7.5 bath · 6,200 sq ft",
    lede:
      "Brand-new Aventura rental with premium finishes, generous square footage, and flexible space for large groups, families, or executive stays.",
    description:
      "Villa Emerald is a brand-new rental home in the exclusive community of Aventura, Florida, just north of Miami. Freshly constructed with attention to detail and premium finishes. Boasting vast spaces, stylish furniture, modern décor, and exquisite vibes, Villa Emerald is perfect for large groups or families looking to take their vacation and business travel to the next level.",
    facts: [
      { label: "Location", value: "Aventura" },
      { label: "Property size", value: "6,200 sq ft" },
      { label: "Bedrooms", value: "9" },
      { label: "Bathrooms", value: "7.5" },
      { label: "Max guests", value: "20" },
      { label: "Check-in", value: "After 3:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "New construction with premium finishes and expansive layout",
      "Suited to large groups, multi-family trips, and business travel",
      "Nine bedrooms and resort-style living spaces",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Pool",
      "Garage",
      "Off-street parking",
    ],
    policyNotes: [
      "Maximum guests: 20.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/emerald/emerald1.jpg",
      "/stays/emerald/emerald2.jpg",
      "/stays/emerald/emerald3.jpg",
      "/stays/emerald/emerald4.jpg",
      "/stays/emerald/emerald5.jpg",
      "/stays/emerald/emerald6.jpg",
      "/stays/emerald/emerald7.jpg",
      "/stays/emerald/emerald8.jpg",
      "/stays/emerald/emerald9.jpg",
      "/stays/emerald/emerald10.jpg",
      "/stays/emerald/emerald11.jpg",
      "/stays/emerald/emerald12.jpg",
      "/stays/emerald/emerald13.jpg",
      "/stays/emerald/emerald14.jpg",
      "/stays/emerald/emerald15.jpg",
      "/stays/emerald/emerald16.jpg",
      "/stays/emerald/emerald17.jpg",
      "/stays/emerald/emerald18.jpg",
      "/stays/emerald/emerald19.jpg",
      "/stays/emerald/emerald20.jpg",
      "/stays/emerald/emerald21.jpg",
      "/stays/emerald/emerald22.jpg",
      "/stays/emerald/emerald23.jpg",
      "/stays/emerald/emerald24.jpg",
      "/stays/emerald/emerald25.jpg",
      "/stays/emerald/emerald26.jpg",
      "/stays/emerald/emerald27.jpg",
      "/stays/emerald/emerald28.jpg",
      "/stays/emerald/emerald29.jpg",
      "/stays/emerald/emerald30.jpg",
      "/stays/emerald/emerald31.jpg",
      "/stays/emerald/emerald32.jpg",
      "/stays/emerald/emerald33.jpg",
      "/stays/emerald/emerald34.jpg",
      "/stays/emerald/emerald35.jpg",
    ],
  },
  {
    id: "fendi",
    name: "Fendi",
    subtitle: "Miami Beach · Biscayne Waterway",
    neighborhood: "Miami Beach",
    cardTagline: "5 bed · 6.5 bath · 5,202 sq ft",
    lede:
      "Contemporary waterfront estate by architect Cheoff Levy Fishman — Biscayne Waterway and bay access at the rear, Miami Beach Golf Club across the street, built for large-scale entertaining.",
    description:
      "This exquisite contemporary residence, designed by Cheoff Levy Fishman, takes advantage of its spectacular setting with the Biscayne Waterway and easy bay access at the rear, and the Miami Beach Golf Club across the street. Designed as a home for entertaining, indoor and outdoor amenities abound: a living room with 28-foot ceilings, a large waterfront dining room, a chef’s kitchen with Wolf and Sub-Zero appliances and rich marble countertops, a family room in its own pavilion, and a waterfront pool with baja shelf and adjacent summer kitchen on a huge ipe wood deck. Upstairs, a large catwalk loft opens to a spectacular master suite with two very large terraces, two dressing rooms, and two water closets.",
    facts: [
      { label: "Location", value: "Miami Beach" },
      { label: "Property size", value: "5,202 sq ft" },
      { label: "Bedrooms", value: "5" },
      { label: "Bathrooms", value: "6.5" },
      { label: "Max guests", value: "10" },
      { label: "Check-in", value: "After 3:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "28-foot ceilings and dramatic waterfront dining and living spaces",
      "Wolf / Sub-Zero kitchen, pool with baja shelf, summer kitchen on ipe deck",
      "Master suite with dual terraces, dressing rooms, and water closets",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
      "Fire pit",
      "Gated private parking",
    ],
    policyNotes: [
      "Maximum guests: 10.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/fendi/fendi1.jpg",
      "/stays/fendi/fendi2.jpg",
      "/stays/fendi/fendi3.jpg",
      "/stays/fendi/fendi4.jpg",
      "/stays/fendi/fendi5.jpg",
      "/stays/fendi/fendi6.jpg",
      "/stays/fendi/fendi7.jpg",
      "/stays/fendi/fendi8.jpg",
      "/stays/fendi/fendi9.jpg",
      "/stays/fendi/fendi10.jpg",
      "/stays/fendi/fendi11.jpg",
      "/stays/fendi/fendi12.jpg",
      "/stays/fendi/fendi13.jpg",
      "/stays/fendi/fendi14.jpg",
      "/stays/fendi/fendi15.jpg",
      "/stays/fendi/fendi16.jpg",
      "/stays/fendi/fendi17.jpg",
      "/stays/fendi/fendi18.jpg",
      "/stays/fendi/fendi19.jpg",
      "/stays/fendi/fendi20.jpg",
      "/stays/fendi/fendi21.jpg",
      "/stays/fendi/fendi22.jpg",
      "/stays/fendi/fendi23.jpg",
      "/stays/fendi/fendi24.jpg",
      "/stays/fendi/fendi25.jpg",
      "/stays/fendi/fendi26.jpg",
      "/stays/fendi/fendi27.jpg",
      "/stays/fendi/fendi28.jpg",
      "/stays/fendi/fendi29.jpg",
      "/stays/fendi/fendi30.jpg",
      "/stays/fendi/fendi31.jpg",
      "/stays/fendi/fendi32.jpg",
      "/stays/fendi/fendi33.jpg",
      "/stays/fendi/fendi34.jpg",
    ],
  },
  {
    id: "granada",
    name: "Granada",
    subtitle: "Coral Gables · pool estate",
    neighborhood: "Coral Gables",
    cardTagline: "10 bed · 10 bath · 5,555 sq ft",
    lede:
      "Spacious Coral Gables pool home with ten bedrooms, game room, and formal living and dining — ideal for large groups near Miracle Mile and Downtown.",
    description:
      "Beautiful new modern pool home with covered terrace and full outdoor pool bathroom. Lush landscape, spacious floor plan, master suite upstairs with large spa-like bathroom and his-and-hers walk-in closets. Ten bedrooms: three downstairs and seven upstairs. Formal light-filled living room, formal dining room, game room with pool table and air hockey, and large kitchen with island. Laundry rooms on each floor. Hurricane impact argon-filled windows and doors. Two-car garage with plenty of outdoor parking. Close to the University of Miami, Miracle Mile, and quick access to Downtown — great for large families, friends, or colleagues.",
    facts: [
      { label: "Location", value: "Coral Gables" },
      { label: "Property size", value: "5,555 sq ft" },
      { label: "Bedrooms", value: "10" },
      { label: "Bathrooms", value: "10" },
      { label: "Max guests", value: "12" },
      { label: "Check-in", value: "After 11:00 am" },
      { label: "Check-out", value: "After 4:00 pm" },
    ],
    highlights: [
      "Ten bedrooms across two levels with game room and pool",
      "Covered terrace, outdoor pool bath, and hurricane-impact glazing",
      "Minutes from University of Miami, Miracle Mile, and Downtown",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
    ],
    policyNotes: [
      "Maximum guests: 12.",
      "Children and pets allowed. Events allowed. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/granada/granada1.jpg",
      "/stays/granada/granada2.webp",
      "/stays/granada/granada3.jpg",
      "/stays/granada/granada4.jpg",
      "/stays/granada/granada5.jpg",
      "/stays/granada/granada6.jpg",
      "/stays/granada/granada7.jpg",
      "/stays/granada/granada8.jpg",
      "/stays/granada/granada9.jpg",
      "/stays/granada/granada10.jpg",
    ],
  },
  {
    id: "largo-resort",
    name: "Largo Resort",
    subtitle: "Key Largo · Tarpon Basin",
    neighborhood: "Key Largo",
    cardTagline: "12 bed · 8 bath · 8,000 sq ft",
    lede:
      "Keys escape on three private acres overlooking Tarpon Basin — main lodge plus retro bungalows, private beach, pool, and lagoon. About one hour south of MIA.",
    description:
      "The Largo Resort property is located in the Florida Keys, Key Largo — not in Miami (about one hour’s drive south from Miami International Airport). This vast property expands across three private acres overlooking the Tarpon Basin in the upper Florida Keys. A high-end, all-inclusive hotel off Route 1 is a four-minute walk from animal encounters at Dolphin Cove, and two miles from the African Queen tourist attraction, featuring the boat from the iconic 1951 film. Split between the main lodge and retro-style bungalows, five airy island-inspired villas each have exposed beam ceilings, flat-screen TVs, and free Wi-Fi. Some add wall beds; one suite offers a whirlpool tub. Amenities include formal dining rooms, a cozy pub-style bar, and a breezy lounge. There is also a private beach, an outdoor pool, and a lagoon.",
    facts: [
      { label: "Location", value: "Key Largo, Florida Keys" },
      { label: "Property size", value: "8,000 sq ft" },
      { label: "Bedrooms", value: "12" },
      { label: "Bathrooms", value: "8" },
      { label: "Max guests", value: "20" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Three private acres on Tarpon Basin with main lodge and bungalows",
      "Private beach, pool, lagoon, and on-site bar and dining spaces",
      "Near Dolphin Cove and the African Queen attraction",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Pool",
      "Waterfront",
      "Boat dock",
    ],
    policyNotes: [
      "Maximum guests: 20.",
      "Children allowed. Pets not permitted. Events allowed. Smoking allowed — confirm house rules when you book.",
    ],
    galleryImages: [
      "/stays/largoresort/largoresort1.jpg",
      "/stays/largoresort/largoresort2.jpg",
      "/stays/largoresort/largoresort3.jpg",
      "/stays/largoresort/largoresort4.jpg",
      "/stays/largoresort/largoresort5.jpg",
      "/stays/largoresort/largoresort6.jpg",
      "/stays/largoresort/largoresort7.jpg",
      "/stays/largoresort/largoresort8.jpg",
      "/stays/largoresort/largoresort9.jpg",
      "/stays/largoresort/largoresort10.jpg",
      "/stays/largoresort/largoresort11.jpg",
      "/stays/largoresort/largoresort12.jpg",
      "/stays/largoresort/largoresort13.jpg",
      "/stays/largoresort/largoresort14.jpg",
      "/stays/largoresort/largoresort15.jpg",
      "/stays/largoresort/largoresort16.jpg",
      "/stays/largoresort/largoresort17.jpg",
      "/stays/largoresort/largoresort18.jpg",
      "/stays/largoresort/largoresort19.jpg",
      "/stays/largoresort/largoresort20.jpg",
      "/stays/largoresort/largoresort21.jpg",
      "/stays/largoresort/largoresort22.jpg",
      "/stays/largoresort/largoresort23.jpg",
      "/stays/largoresort/largoresort24.jpg",
      "/stays/largoresort/largoresort25.jpg",
      "/stays/largoresort/largoresort26.jpg",
      "/stays/largoresort/largoresort27.jpg",
      "/stays/largoresort/largoresort28.jpg",
      "/stays/largoresort/largoresort29.jpg",
      "/stays/largoresort/largoresort30.jpg",
      "/stays/largoresort/largoresort31.jpg",
      "/stays/largoresort/largoresort32.jpg",
      "/stays/largoresort/largoresort33.jpg",
      "/stays/largoresort/largoresort34.jpg",
      "/stays/largoresort/largoresort35.jpg",
      "/stays/largoresort/largoresort36.jpg",
      "/stays/largoresort/largoresort37.jpg",
    ],
  },
  {
    id: "moet",
    name: "Moët",
    subtitle: "North Miami · waterfront",
    neighborhood: "North Miami",
    cardTagline: "4 bed · 3.5 bath · 3,300 sq ft",
    lede:
      "Updated waterfront four-bedroom with open kitchen, Miele appliances, spa pool, and 75 ft of canal frontage with boat lift and jet-ski dock.",
    description:
      "Spectacular updated waterfront four-bedroom, three-and-a-half-bath home. Open floor plan with a large kitchen island perfect for entertaining. High-end finishes throughout: Miele appliances, water views from every room, porcelain and travertine floors. The master suite has a large terrace overlooking the pool and water. Large master bath with dual sinks, dual showers, and jacuzzi. Covered outdoor kitchen, LED recessed lighting, large pool with spa. New dock on a 75-foot-wide canal with a 24K lb boat lift and separate jet-ski dock — only a few homes from open bay. Impact windows and doors. Two-car garage converted into a full gym plus large private driveway. Laundry room and large pantry.",
    facts: [
      { label: "Location", value: "North Miami" },
      { label: "Property size", value: "3,300 sq ft" },
      { label: "Bedrooms", value: "4" },
      { label: "Bathrooms", value: "3.5" },
      { label: "Max guests", value: "10" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Miele kitchen, spa pool, and water views throughout",
      "75 ft canal frontage with lift, jet-ski dock, and quick bay access",
      "Gym in converted garage, covered outdoor kitchen, impact glazing",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
    ],
    policyNotes: [
      "Maximum guests: 10.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/moet/moet1.webp",
      "/stays/moet/moet2.jpg",
      "/stays/moet/moet3.jpg",
      "/stays/moet/moet4.jpg",
      "/stays/moet/moet5.jpg",
      "/stays/moet/moet6.jpg",
      "/stays/moet/moet7.jpg",
      "/stays/moet/moet8.jpg",
      "/stays/moet/moet9.jpg",
      "/stays/moet/moet10.jpg",
    ],
  },
  {
    id: "playa-castillo",
    name: "Playa Castillo",
    subtitle: "Venetian Islands · Biscayne Island",
    neighborhood: "Venetian Islands",
    cardTagline: "6 bed · 3.5 bath · 3,333 sq ft",
    lede:
      "Newly renovated six-bedroom villa on Biscayne Island with bay and skyline views, courtyard pool, and cabana-style covered patio for dining and lounging.",
    description:
      "Step into luxury with this chic Miami-style six-bedroom, three-and-a-half-bathroom modern villa with stunning views of Biscayne Bay and the Miami skyline. The home spans over 3,333 square feet and is one of a few single-family homes on highly desired Biscayne Island, facing south. Newly renovated with high ceilings, stainless steel appliances, stone countertops, and everything you need for entertaining. Enjoy a courtyard garden with a heated swimming pool and a covered seating area for shade. Indoor and outdoor entertaining spaces include balconies, a pool, and outdoor seating. Dine or relax on the covered patio with bay and skyline views. Flat-screen TVs in the bedrooms and living room; outdoor grill for summer barbecues — a modern, stylish Miami-chic retreat.",
    facts: [
      { label: "Location", value: "Biscayne Island · Venetian Islands area" },
      { label: "Property size", value: "3,333 sq ft" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "3.5" },
      { label: "Max guests", value: "12" },
      { label: "Check-in", value: "After 3:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "South-facing Biscayne Island home with bay and skyline views",
      "Heated pool, courtyard garden, and cabana-style covered patio",
      "Balconies, outdoor grill, and indoor–outdoor entertaining",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Pool",
      "Patio",
      "Off-street parking",
    ],
    policyNotes: [
      "Maximum guests: 12.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/playacastillo/playacastillo1.jpg",
      "/stays/playacastillo/playacastillo2.jpg",
      "/stays/playacastillo/playacastillo3.jpg",
      "/stays/playacastillo/playacastillo4.jpg",
      "/stays/playacastillo/playacastillo5.jpg",
      "/stays/playacastillo/playacastillo6.jpg",
      "/stays/playacastillo/playacastillo7.jpg",
      "/stays/playacastillo/playacastillo8.jpg",
      "/stays/playacastillo/playacastillo9.jpg",
      "/stays/playacastillo/playacastillo10.jpg",
      "/stays/playacastillo/playacastillo11.jpg",
      "/stays/playacastillo/playacastillo12.jpg",
      "/stays/playacastillo/playacastillo13.jpg",
      "/stays/playacastillo/playacastillo14.jpg",
      "/stays/playacastillo/playacastillo15.jpg",
      "/stays/playacastillo/playacastillo16.jpg",
      "/stays/playacastillo/playacastillo17.jpg",
      "/stays/playacastillo/playacastillo18.jpg",
      "/stays/playacastillo/playacastillo19.jpg",
      "/stays/playacastillo/playacastillo20.jpg",
      "/stays/playacastillo/playacastillo21.jpg",
      "/stays/playacastillo/playacastillo22.jpg",
      "/stays/playacastillo/playacastillo23.jpg",
      "/stays/playacastillo/playacastillo24.jpg",
      "/stays/playacastillo/playacastillo25.jpg",
      "/stays/playacastillo/playacastillo26.jpg",
      "/stays/playacastillo/playacastillo27.jpg",
      "/stays/playacastillo/playacastillo28.jpg",
      "/stays/playacastillo/playacastillo29.jpg",
      "/stays/playacastillo/playacastillo30.jpg",
      "/stays/playacastillo/playacastillo31.jpg",
      "/stays/playacastillo/playacastillo32.jpg",
      "/stays/playacastillo/playacastillo33.jpg",
      "/stays/playacastillo/playacastillo34.jpg",
      "/stays/playacastillo/playacastillo35.jpg",
      "/stays/playacastillo/playacastillo36.jpg",
    ],
  },
  {
    id: "bodrum",
    name: "Bodrum",
    subtitle: "Miami Shores · waterfront",
    neighborhood: "Miami Shores",
    cardTagline: "8 bed · 4.5 bath · 3,500 sq ft",
    lede:
      "Eight-bedroom Miami Shores waterfront villa with room for large groups — secluded water frontage and city views.",
    description:
      "Luxury eight-bedroom villa rental in Miami with secluded waterfront and city views — built for entertaining and bay days with private water access.",
    facts: [
      { label: "Location", value: "Miami Shores" },
      { label: "Property size", value: "3,500 sq ft" },
      { label: "Bedrooms", value: "8" },
      { label: "Bathrooms", value: "4.5" },
      { label: "Max guests", value: "16" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Eight bedrooms for large groups",
      "Waterfront with dock access",
      "City views and flexible entertaining spaces",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Pool",
      "Waterfront",
      "Boat dock",
    ],
    policyNotes: [
      "Maximum guests: 16.",
      "Children and pets allowed. Events allowed. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/bodrum/bodrum1.jpg",
      "/stays/bodrum/bodrum2.jpg",
      "/stays/bodrum/bodrum3.jpg",
      "/stays/bodrum/bodrum4.jpg",
      "/stays/bodrum/bodrum5.jpg",
      "/stays/bodrum/bodrum6.jpg",
      "/stays/bodrum/bodrum7.jpg",
      "/stays/bodrum/bodrum8.jpg",
      "/stays/bodrum/bodrum9.jpg",
      "/stays/bodrum/bodrum10.jpg",
      "/stays/bodrum/bodrum11.jpg",
      "/stays/bodrum/bodrum12.jpg",
      "/stays/bodrum/bodrum13.jpg",
      "/stays/bodrum/bodrum14.jpg",
      "/stays/bodrum/bodrum15.jpg",
      "/stays/bodrum/bodrum16.jpg",
      "/stays/bodrum/bodrum17.jpg",
      "/stays/bodrum/bodrum18.jpg",
      "/stays/bodrum/bodrum19.jpg",
      "/stays/bodrum/bodrum20.jpg",
      "/stays/bodrum/bodrum21.jpg",
      "/stays/bodrum/bodrum22.jpg",
      "/stays/bodrum/bodrum23.jpg",
      "/stays/bodrum/bodrum24.jpg",
      "/stays/bodrum/bodrum25.jpg",
      "/stays/bodrum/bodrum26.jpg",
      "/stays/bodrum/bodrum27.jpg",
      "/stays/bodrum/bodrum28.jpg",
      "/stays/bodrum/bodrum29.jpg",
      "/stays/bodrum/bodrum30.jpg",
    ],
  },
  {
    id: "casa-blu",
    name: "Casa Blu",
    subtitle: "Upper East Side · waterfront",
    neighborhood: "Upper East Side",
    cardTagline: "7 bed · 8 bath · 8,000 sq ft",
    lede:
      "The “Miami Blue House” on the Little River — ~350 ft of waterfront on a gated half-acre pie lot, with an 80 ft pool, massive tiki hut, and bay-to-canal dockage.",
    description:
      "At the mouth of the Little River sits the Miami Blue House, a sprawling estate surrounded by about 350 feet of waterfront. Gaze at dolphin visits, manatees, and skyline views from this gated waterfront home at the end of a cul-de-sac, on a corner pie-shaped lot of roughly half an acre from the bay to the canal entrance — safe dockage with about 300 ft of seawall. The elegant 8,000 sq ft, two-story home with a three-car garage features a vast two-level master suite with private screening area, dining, and balcony. The West Wing includes a queen guest room with water views, a twin room that doubles as service quarters, and a chef’s kitchen with full walk-in. A bar and breakfast nook sit surrounded by Biscayne views. A formal dining room seats fourteen with room for ten more; a recreation room offers a pool table and arcade with 200 classic games. The East Wing living room features blue and gold accents, a 70″ TV, and professional sound. Upstairs, three more bedrooms include the Blue and Sunrise rooms (three queens each) and the Lime room — all with bay views and a wraparound balcony. Outside: seating for large groups, an 80-foot heated pool and jacuzzi in an hourglass layout, and a tiki hut over 2,500 sq ft with pizza oven, smoker, dining for 40, outdoor TV, sectionals, waterfall, LED jacuzzi, and more.",
    facts: [
      { label: "Location", value: "Upper East Side · Little River" },
      { label: "Property size", value: "8,000 sq ft" },
      { label: "Bedrooms", value: "7" },
      { label: "Bathrooms", value: "8" },
      { label: "Max guests", value: "20" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Gated estate with ~350 ft waterfront and ~300 ft seawall",
      "80 ft heated pool, oversized tiki hut, and full outdoor kitchen",
      "Theater-style master wing, arcade & game room, wraparound balconies",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
    ],
    policyNotes: [
      "Maximum guests: 20.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/casablu/casablu1.jpg",
      "/stays/casablu/casablu2.jpg",
      "/stays/casablu/casablu3.jpg",
      "/stays/casablu/casablu4.jpg",
      "/stays/casablu/casablu5.jpg",
      "/stays/casablu/casablu6.jpg",
      "/stays/casablu/casablu7.jpg",
      "/stays/casablu/casablu8.jpg",
      "/stays/casablu/casablu9.jpg",
      "/stays/casablu/casablu10.jpg",
      "/stays/casablu/casablu11.jpg",
      "/stays/casablu/casablu12.jpg",
      "/stays/casablu/casablu13.jpg",
      "/stays/casablu/casablu14.jpg",
      "/stays/casablu/casablu15.jpg",
      "/stays/casablu/casablu16.jpg",
      "/stays/casablu/casablu17.jpg",
      "/stays/casablu/casablu18.jpg",
      "/stays/casablu/casablu19.jpg",
      "/stays/casablu/casablu20.jpg",
      "/stays/casablu/casablu21.jpg",
      "/stays/casablu/casablu22.jpg",
      "/stays/casablu/casablu23.jpg",
      "/stays/casablu/casablu24.jpg",
      "/stays/casablu/casablu25.jpg",
      "/stays/casablu/casablu26.jpg",
      "/stays/casablu/casablu27.jpg",
      "/stays/casablu/casablu28.jpg",
      "/stays/casablu/casablu29.jpg",
      "/stays/casablu/casablu30.jpg",
      "/stays/casablu/casablu31.jpg",
      "/stays/casablu/casablu32.jpg",
      "/stays/casablu/casablu33.jpg",
      "/stays/casablu/casablu34.jpg",
      "/stays/casablu/casablu35.jpg",
      "/stays/casablu/casablu36.jpg",
      "/stays/casablu/casablu37.jpg",
      "/stays/casablu/casablu38.jpg",
      "/stays/casablu/casablu39.jpg",
      "/stays/casablu/casablu40.jpg",
      "/stays/casablu/casablu41.jpg",
      "/stays/casablu/casablu42.jpg",
      "/stays/casablu/casablu43.jpg",
      "/stays/casablu/casablu44.jpg",
    ],
  },
  {
    id: "castillo",
    name: "Castillo",
    subtitle: "Miami Shores · estate",
    neighborhood: "Miami Shores",
    cardTagline: "8 bed · 5.5 bath · 6,000 sq ft",
    lede:
      "Tudor and Mediterranean revival exterior meets modern interiors — theater, billiards, and a resort pool with rock slide and hot tub.",
    description:
      "Villa Castillo’s Miami architecture blends modern interiors with Tudor and Mediterranean revival exteriors for a dramatic first impression. A huge eat-in chef’s kitchen, family room with HD TV, dining room with 30-foot ceilings, parlor with billiards, and a movie theater with Dolby sound, Xbox, theater seating, blackout shades, and full wet bar. Outside: pool and lounge with custom rock slide and hot tub in a private, gated oasis. Just off the patio, a master suite features a jacuzzi tub and steam shower in his-and-hers baths.",
    facts: [
      { label: "Location", value: "Miami Shores" },
      { label: "Property size", value: "6,000 sq ft" },
      { label: "Bedrooms", value: "8" },
      { label: "Bathrooms", value: "5.5" },
      { label: "Max guests", value: "16" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "30-foot dining ceilings, theater, and billiards parlor",
      "Pool with custom rock slide, spa, and private gated grounds",
      "Master wing with jacuzzi and steam shower",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Pool",
    ],
    policyNotes: [
      "Maximum guests: 16.",
      "Children allowed. Pets not permitted. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/castillo/castillo1.jpg",
      "/stays/castillo/castillo2.jpg",
      "/stays/castillo/castillo3.jpg",
      "/stays/castillo/castillo4.jpg",
      "/stays/castillo/castillo5.jpg",
      "/stays/castillo/castillo6.jpg",
      "/stays/castillo/castillo7.jpg",
      "/stays/castillo/castillo8.jpg",
      "/stays/castillo/castillo9.jpg",
      "/stays/castillo/castillo10.jpg",
      "/stays/castillo/castillo11.jpg",
      "/stays/castillo/castillo12.jpg",
      "/stays/castillo/castillo13.jpg",
      "/stays/castillo/castillo14.jpg",
      "/stays/castillo/castillo15.jpg",
      "/stays/castillo/castillo16.jpg",
      "/stays/castillo/castillo17.jpg",
      "/stays/castillo/castillo18.jpg",
      "/stays/castillo/castillo19.jpg",
      "/stays/castillo/castillo20.jpg",
      "/stays/castillo/castillo21.jpg",
      "/stays/castillo/castillo22.jpg",
      "/stays/castillo/castillo23.jpg",
      "/stays/castillo/castillo24.jpg",
      "/stays/castillo/castillo25.jpg",
      "/stays/castillo/castillo26.jpg",
      "/stays/castillo/castillo27.jpg",
    ],
  },
  {
    id: "chanel",
    name: "Chanel",
    subtitle: "Hollywood · Hollywood Lakes",
    neighborhood: "Hollywood",
    cardTagline: "6 bed · 4 bath · 4,500 sq ft",
    lede:
      "Waterfront Hollywood Lakes home with no fixed bridges to the ocean — Pebble Tec pool, beach shelf, spa, and travertine patio with summer kitchen option.",
    description:
      "Live on the water with no fixed bridges and easy ocean access. Architecturally designed Pebble Tec pool with beach-shelf entry, spillover spa, bubblers, waterfall, and moat. Spacious bright living space, floor-to-ceiling glass, and new Brazilian wood floors. Open kitchen with gas Thermador cooktop and Sub-Zero refrigerator. In prestigious Hollywood Lakes, north of Miami and south of Fort Lauderdale — short bike ride to Hollywood Beach. Two second-level balconies overlook the pool and water. Large travertine patio with optional summer kitchen (gas connection). Six bedrooms and four baths with flexible layouts for media, office, summer kitchen, or play room. Hurricane impact windows and doors.",
    facts: [
      { label: "Location", value: "Hollywood Lakes, FL" },
      { label: "Property size", value: "4,500 sq ft" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "4" },
      { label: "Max guests", value: "12" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Direct water access without fixed bridges toward the ocean",
      "Resort pool with beach shelf, spa, waterfall, and moat",
      "Balconies over the water; impact glass throughout",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
      "Pool table",
      "Table tennis",
    ],
    policyNotes: [
      "Maximum guests: 12.",
      "Children and pets allowed. Events not permitted. No smoking indoors.",
      "Outdoor noise must be kept to library-quiet levels from 11:00 pm to 8:00 am.",
      "Absolutely no parties anywhere on the premises. Fines may exceed $5,000 per occurrence; notice to vacate may be issued for party, noise, or police complaints. City or police fines related to guest conduct may be billed to the guest; the security deposit may be forfeited. Noise violations may incur fines up to $5,000 from the deposit.",
      "Photo ID required at check-in; the booking guest must check in. No outside music or DJ equipment — violation may mean immediate removal and loss of deposit. Drive slowly in the neighborhood — no more than four cars in the driveway.",
    ],
    galleryImages: [
      "/stays/chanel/chanel1.webp",
      "/stays/chanel/chanel2.jpg",
      "/stays/chanel/chanel3.jpg",
      "/stays/chanel/chanel4.jpg",
      "/stays/chanel/chanel5.jpg",
      "/stays/chanel/chanel6.jpg",
      "/stays/chanel/chanel7.jpg",
      "/stays/chanel/chanel8.jpg",
      "/stays/chanel/chanel9.jpg",
      "/stays/chanel/chanel10.jpg",
      "/stays/chanel/chanel11.jpg",
      "/stays/chanel/chanel12.jpg",
      "/stays/chanel/chanel13.jpg",
      "/stays/chanel/chanel14.jpg",
      "/stays/chanel/chanel15.jpg",
      "/stays/chanel/chanel16.jpg",
      "/stays/chanel/chanel17.jpg",
      "/stays/chanel/chanel18.jpg",
      "/stays/chanel/chanel19.jpg",
      "/stays/chanel/chanel20.jpg",
      "/stays/chanel/chanel21.jpg",
      "/stays/chanel/chanel22.jpg",
      "/stays/chanel/chanel23.jpg",
      "/stays/chanel/chanel24.jpg",
      "/stays/chanel/chanel25.jpg",
      "/stays/chanel/chanel26.jpg",
      "/stays/chanel/chanel27.jpg",
      "/stays/chanel/chanel28.jpg",
      "/stays/chanel/chanel29.jpg",
    ],
  },
  {
    id: "dolce",
    name: "Dolce",
    subtitle: "Venetian Islands · waterfront",
    neighborhood: "Venetian Islands",
    cardTagline: "8 bed · 7.5 bath · 6,000 sq ft",
    lede:
      "Expansive Venetian Islands estate with skyline views — eight bedrooms, gracious public rooms, and a modern-classic balance of privacy and scale.",
    description:
      "Villa Dolce is an expansive luxury property, updated and balanced throughout, framed by views of the Miami skyline. Privacy and modernist classicism across panoramic views of Miami Beach and the mainland. Superb proportions and finely wrought details across eight bedrooms, seven and a half bathrooms, and generous public rooms.",
    facts: [
      { label: "Location", value: "Venetian Islands" },
      { label: "Property size", value: "6,000 sq ft" },
      { label: "Bedrooms", value: "8" },
      { label: "Bathrooms", value: "7.5" },
      { label: "Max guests", value: "16" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Skyline views toward Miami Beach and the mainland",
      "Eight bedrooms and generous formal and informal spaces",
      "Waterfront Venetian Islands setting with private, discreet grounds",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
    ],
    policyNotes: [
      "Maximum guests: 16.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/dolce/dolce1.jpg",
      "/stays/dolce/dolce2.jpg",
      "/stays/dolce/dolce3.jpg",
      "/stays/dolce/dolce4.jpg",
      "/stays/dolce/dolce5.jpg",
      "/stays/dolce/dolce6.jpg",
      "/stays/dolce/dolce7.jpg",
      "/stays/dolce/dolce8.jpg",
      "/stays/dolce/dolce9.jpg",
      "/stays/dolce/dolce10.jpg",
      "/stays/dolce/dolce11.jpg",
      "/stays/dolce/dolce12.jpg",
      "/stays/dolce/dolce13.jpg",
      "/stays/dolce/dolce14.jpg",
      "/stays/dolce/dolce15.jpg",
      "/stays/dolce/dolce16.jpg",
      "/stays/dolce/dolce17.jpg",
      "/stays/dolce/dolce18.jpg",
      "/stays/dolce/dolce19.jpg",
      "/stays/dolce/dolce20.jpg",
      "/stays/dolce/dolce21.jpg",
      "/stays/dolce/dolce22.jpg",
      "/stays/dolce/dolce23.jpg",
      "/stays/dolce/dolce24.jpg",
      "/stays/dolce/dolce25.jpg",
      "/stays/dolce/dolce26.jpg",
      "/stays/dolce/dolce27.jpg",
    ],
  },
  {
    id: "estrella-palacia",
    name: "Estrella Palacia",
    subtitle: "Miami Beach · Star Island",
    neighborhood: "Miami Beach",
    cardTagline: "11 bed · 13 bath · 24,600 sq ft",
    lede:
      "Star Island landmark — up to eleven en-suite bedrooms, full staff, spa, commercial elevator, and six-star amenities across 24,000+ sq ft interior.",
    description:
      "Roughly 24,000 sq ft of interior space and 40,000 sq ft total — built around the historic renovation of architect C. Walter De Garmo’s original guest villa. On world-famous Star Island, configure five to eleven bedrooms with en-suite baths, Cavalli furnishings, and six-star hotel-level amenities. Chef’s kitchen with premium appliances and five cooking methods, commercial elevator, Crestron with Function One speakers and Pioneer DJ setup, full spa with steam, sauna, massage rooms, and an oversized gym. Housekeeping staff and full-time chef on site; concierge butler service can arrange additional requests. Available for six-month-plus terms and permitted photo and video shoots.",
    facts: [
      { label: "Location", value: "Star Island, Miami Beach" },
      { label: "Property size", value: "24,600 sq ft" },
      { label: "Bedrooms", value: "11" },
      { label: "Bathrooms", value: "13" },
      { label: "Max guests", value: "20" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Historic De Garmo estate footprint with modern amenities",
      "On-site chef, housekeeping, and butler-style concierge",
      "Spa, gym, commercial elevator, and professional entertainment",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
      "Pool / guest house",
    ],
    policyNotes: [
      "Maximum guests: 20.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/estrellapalacia/estrellapalacia1.jpg",
      "/stays/estrellapalacia/estrellapalacia2.jpg",
      "/stays/estrellapalacia/estrellapalacia3.jpg",
      "/stays/estrellapalacia/estrellapalacia4.jpg",
      "/stays/estrellapalacia/estrellapalacia5.jpg",
      "/stays/estrellapalacia/estrellapalacia7.jpg",
      "/stays/estrellapalacia/estrellapalacia8.jpg",
      "/stays/estrellapalacia/estrellapalacia9.jpg",
      "/stays/estrellapalacia/estrellapalacia10.jpg",
      "/stays/estrellapalacia/estrellapalacia12.jpg",
      "/stays/estrellapalacia/estrellapalacia13.jpg",
      "/stays/estrellapalacia/estrellapalacia14.jpg",
      "/stays/estrellapalacia/estrellapalacia15.jpg",
      "/stays/estrellapalacia/estrellapalacia16.jpg",
      "/stays/estrellapalacia/estrellapalacia17.jpg",
      "/stays/estrellapalacia/estrellapalacia18.jpg",
      "/stays/estrellapalacia/estrellapalacia19.jpg",
      "/stays/estrellapalacia/estrellapalacia20.jpg",
      "/stays/estrellapalacia/estrellapalacia21.jpg",
      "/stays/estrellapalacia/estrellapalacia22.jpg",
      "/stays/estrellapalacia/estrellapalacia23.jpg",
      "/stays/estrellapalacia/estrellapalacia24.jpg",
      "/stays/estrellapalacia/estrellapalacia25.jpg",
      "/stays/estrellapalacia/estrellapalacia26.jpg",
      "/stays/estrellapalacia/estrellapalacia27.jpg",
      "/stays/estrellapalacia/estrellapalacia28.jpg",
      "/stays/estrellapalacia/estrellapalacia29.jpg",
      "/stays/estrellapalacia/estrellapalacia30.jpg",
      "/stays/estrellapalacia/estrellapalacia31.jpg",
    ],
  },
  {
    id: "glacia",
    name: "Glacia",
    subtitle: "Venetian Islands · waterfront",
    neighborhood: "Venetian Islands",
    cardTagline: "4 bed · 4 bath · 5,300 sq ft",
    lede:
      "Modern glass-walled waterfront villa on the Venetian Islands — infinity pool, 60 ft of frontage, and rooftop terraces over Biscayne Bay.",
    description:
      "Luxury modern waterfront villa in Miami’s exclusive Venetian Islands, with soaring ceilings and walls of glass framing panoramic Biscayne Bay views. Straight sight lines, modern furnishings, and high-end finishes including glass showers and a rectangular porcelain tub overlooking the bay. Open floor plan, lavish master suite, walk-in closets, infinity pool, and IPE boat dock. Rooftop terraces and 60 feet of waterfront with a large covered outdoor entertaining area.",
    facts: [
      { label: "Location", value: "Venetian Islands" },
      { label: "Property size", value: "5,300 sq ft" },
      { label: "Bedrooms", value: "4" },
      { label: "Bathrooms", value: "4" },
      { label: "Max guests", value: "8" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Panoramic bay views through floor-to-ceiling glass",
      "Infinity pool, IPE dock, and rooftop terraces",
      "60 ft waterfront with covered outdoor entertaining",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
    ],
    policyNotes: [
      "Maximum guests: 8.",
      "Children allowed. Pets not permitted. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/glacia/glacia1.jpg",
      "/stays/glacia/glacia2.jpg",
      "/stays/glacia/glacia3.jpg",
      "/stays/glacia/glacia4.jpg",
      "/stays/glacia/glacia5.jpg",
      "/stays/glacia/glacia6.jpg",
      "/stays/glacia/glacia7.jpg",
      "/stays/glacia/glacia8.jpg",
      "/stays/glacia/glacia9.jpg",
      "/stays/glacia/glacia10.jpg",
      "/stays/glacia/glacia11.jpg",
      "/stays/glacia/glacia12.jpg",
      "/stays/glacia/glacia13.jpg",
      "/stays/glacia/glacia14.jpg",
      "/stays/glacia/glacia15.jpg",
      "/stays/glacia/glacia16.jpg",
      "/stays/glacia/glacia17.jpg",
    ],
  },
  {
    id: "godiva",
    name: "Godiva",
    subtitle: "Golden Beach · oceanfront",
    neighborhood: "Golden Beach",
    cardTagline: "6 bed · 8 bath · 9,000 sq ft",
    lede:
      "New nine-thousand-square-foot Golden Beach residence with Atlantic views, glass atrium, private elevator, Italian kitchen, and smart-home automation.",
    description:
      "Turn-key villa in exclusive Golden Beach, just north of Miami Beach — a 9,000 sq ft architectural jewel with ocean views. Six bedrooms and eight baths feature a 20-foot glass atrium with private elevator, imported marble floors, Italian custom kitchen, home theater, and space for a private art gallery. Full electronic Lutron automation. Outside: lap pool, cabana, hot tub, outdoor dining, babbling pond, four terraces, and a two-car garage. Newly completed three-level single-family residence along the Atlantic with 3,000 sq ft of ocean-view terraces.",
    facts: [
      { label: "Location", value: "Golden Beach" },
      { label: "Property size", value: "9,000 sq ft" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "8" },
      { label: "Max guests", value: "12" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Atlantic-front Golden Beach with terraces and ocean views",
      "Private elevator, Italian kitchen, theater, and smart-home control",
      "Lap pool, cabana, hot tub, and multiple outdoor terraces",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
    ],
    policyNotes: [
      "Maximum guests: 12.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/godiva/godiva1.jpg",
      "/stays/godiva/godiva2.jpg",
      "/stays/godiva/godiva3.jpg",
      "/stays/godiva/godiva4.jpg",
      "/stays/godiva/godiva5.jpg",
      "/stays/godiva/godiva6.jpg",
      "/stays/godiva/godiva7.jpg",
      "/stays/godiva/godiva8.jpg",
      "/stays/godiva/godiva9.jpg",
      "/stays/godiva/godiva10.jpg",
      "/stays/godiva/godiva11.jpg",
      "/stays/godiva/godiva12.jpg",
      "/stays/godiva/godiva13.jpg",
      "/stays/godiva/godiva14.jpg",
      "/stays/godiva/godiva15.jpg",
      "/stays/godiva/godiva16.jpg",
      "/stays/godiva/godiva17.jpg",
      "/stays/godiva/godiva18.jpg",
    ],
  },
  {
    id: "manuela",
    name: "Manuela",
    subtitle: "Miami Beach · Hibiscus Island",
    neighborhood: "Miami Beach",
    cardTagline: "6 bed · 7.5 bath · 6,700 sq ft",
    lede:
      "Contemporary Hibiscus Island waterfront villa — Miele, Wolf & Sub-Zero, theater, gym, infinity lap pool, and rooftop lounge with 360° views.",
    description:
      "Stunning contemporary six-bedroom waterfront villa on Hibiscus Island with westerly wide-bay sunset views. Open living, dining, and kitchen with Miele, Wolf, and Sub-Zero appliances; built-in bar; movie theatre with leather recliners; gym; and outdoor kitchen. All second-floor bedrooms have balconies with water views. Heated infinity-edge 12 ft lap pool with shallow sun area and hot tub with fire pit. Expansive rooftop lounge with 360° views. Eighty-five feet of water frontage with boat lift and dock.",
    facts: [
      { label: "Location", value: "Hibiscus Island, Miami Beach" },
      { label: "Property size", value: "6,700 sq ft" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "7.5" },
      { label: "Max guests", value: "12" },
      { label: "Check-in", value: "After 2:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Sunset-facing bay views from living areas and bedroom balconies",
      "Infinity lap pool, spa, fire pit, and rooftop lounge",
      "Theatre, gym, and 85 ft waterfront with lift and dock",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
    ],
    policyNotes: [
      "Maximum guests: 12.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/manuela/manuela1.jpg",
      "/stays/manuela/manuela2.jpg",
      "/stays/manuela/manuela3.jpg",
      "/stays/manuela/manuela4.jpg",
      "/stays/manuela/manuela5.jpg",
      "/stays/manuela/manuela6.jpg",
      "/stays/manuela/manuela7.jpg",
      "/stays/manuela/manuela8.jpg",
      "/stays/manuela/manuela9.jpg",
      "/stays/manuela/manuela10.jpg",
      "/stays/manuela/manuela11.jpg",
      "/stays/manuela/manuela12.jpg",
      "/stays/manuela/manuela13.jpg",
      "/stays/manuela/manuela14.jpg",
      "/stays/manuela/manuela15.jpg",
      "/stays/manuela/manuela16.jpg",
      "/stays/manuela/manuela17.jpg",
      "/stays/manuela/manuela18.jpg",
      "/stays/manuela/manuela19.jpg",
      "/stays/manuela/manuela20.jpg",
      "/stays/manuela/manuela21.jpg",
      "/stays/manuela/manuela22.jpg",
      "/stays/manuela/manuela23.jpg",
      "/stays/manuela/manuela24.jpg",
      "/stays/manuela/manuela25.jpg",
      "/stays/manuela/manuela26.jpg",
      "/stays/manuela/manuela27.jpg",
      "/stays/manuela/manuela28.jpg",
      "/stays/manuela/manuela29.jpg",
      "/stays/manuela/manuela30.jpg",
      "/stays/manuela/manuela31.jpg",
      "/stays/manuela/manuela32.jpg",
      "/stays/manuela/manuela33.jpg",
      "/stays/manuela/manuela34.jpg",
      "/stays/manuela/manuela35.jpg",
      "/stays/manuela/manuela36.jpg",
      "/stays/manuela/manuela37.jpg",
      "/stays/manuela/manuela38.jpg",
    ],
  },
  {
    id: "mariola",
    name: "Mariola",
    subtitle: "Coral Gables · near Biltmore",
    neighborhood: "Coral Gables",
    cardTagline: "5 bed · 7 bath · 5,000 sq ft",
    lede:
      "New Coral Gables build near the Biltmore — 22 ft ceilings at the pool, Italian kitchen, movie room, library, and rooftop deck.",
    description:
      "New construction in prestigious Coral Gables, minutes from the Biltmore Hotel golf and spa. Enter through an 11-foot custom impact-glass pivot door; serene views of a 45-foot pool from the living room with 22-foot ceilings, mature trees, and a garden for children. Italian kitchen opens to dining and the backyard BBQ. Terraces for indoor–outdoor entertaining; porcelain and oak floors. Movie room, library, and rooftop deck. Concierge can arrange chefs, yacht days, and white-glove services — tailored to your stay.",
    facts: [
      { label: "Location", value: "Coral Gables" },
      { label: "Property size", value: "5,000 sq ft" },
      { label: "Bedrooms", value: "5" },
      { label: "Bathrooms", value: "7" },
      { label: "Max guests", value: "10" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Dramatic entry and double-height living overlooking the pool",
      "Italian kitchen, movie room, library, and rooftop deck",
      "Near Biltmore golf & spa; lush private grounds",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Outdoor kitchen",
    ],
    policyNotes: [
      "Maximum guests: 10.",
      "Children and pets allowed. Events allowed. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/mariola/mariola1.jpg",
      "/stays/mariola/mariola2.jpg",
      "/stays/mariola/mariola3.jpg",
      "/stays/mariola/mariola4.jpg",
      "/stays/mariola/mariola5.jpg",
      "/stays/mariola/mariola6.jpg",
      "/stays/mariola/mariola7.jpg",
      "/stays/mariola/mariola8.jpg",
      "/stays/mariola/mariola9.jpg",
      "/stays/mariola/mariola10.jpg",
      "/stays/mariola/mariola11.jpg",
      "/stays/mariola/mariola12.jpg",
      "/stays/mariola/mariola13.jpg",
      "/stays/mariola/mariola14.jpg",
      "/stays/mariola/mariola15.jpg",
      "/stays/mariola/mariola16.jpg",
      "/stays/mariola/mariola17.jpg",
      "/stays/mariola/mariola18.jpg",
      "/stays/mariola/mariola19.jpg",
      "/stays/mariola/mariola20.jpg",
      "/stays/mariola/mariola21.jpg",
      "/stays/mariola/mariola22.jpg",
    ],
  },
  {
    id: "nautilus",
    name: "Nautilus",
    subtitle: "Miami Beach · waterfront",
    neighborhood: "Miami Beach",
    cardTagline: "5 bed · 6.5 bath · 5,406 sq ft",
    lede:
      "Modern waterfront residence with soaring ceilings, summer kitchen, cabana, guest house, staff quarters, and dock.",
    description:
      "Chic modern waterfront residence designed for today’s lifestyle. Open floor plan with soaring ceilings and water views throughout. Covered terrace with contemporary pool, bar, summer kitchen, cabana, and endless views. Grand living room, gourmet kitchen, dining room, and separate guest house with private entrance. Staff quarters, dock, and ample parking.",
    facts: [
      { label: "Location", value: "Miami Beach" },
      { label: "Property size", value: "5,406 sq ft" },
      { label: "Bedrooms", value: "5" },
      { label: "Bathrooms", value: "6.5" },
      { label: "Max guests", value: "10" },
      { label: "Check-in", value: "After 2:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Water views from principal living spaces",
      "Guest house, staff quarters, dock, and generous parking",
      "Pool terrace with summer kitchen and cabana",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
    ],
    policyNotes: [
      "Maximum guests: 10.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/nautilus/nautilus1.jpg",
      "/stays/nautilus/nautilus2.jpg",
      "/stays/nautilus/nautilus3.jpg",
      "/stays/nautilus/nautilus4.jpg",
      "/stays/nautilus/nautilus5.jpg",
      "/stays/nautilus/nautilus6.jpg",
      "/stays/nautilus/nautilus7.jpg",
      "/stays/nautilus/nautilus8.jpg",
      "/stays/nautilus/nautilus9.jpg",
      "/stays/nautilus/nautilus10.jpg",
      "/stays/nautilus/nautilus11.jpg",
      "/stays/nautilus/nautilus12.jpg",
      "/stays/nautilus/nautilus13.jpg",
      "/stays/nautilus/nautilus14.jpg",
      "/stays/nautilus/nautilus15.jpg",
      "/stays/nautilus/nautilus16.jpg",
      "/stays/nautilus/nautilus17.jpg",
      "/stays/nautilus/nautilus18.jpg",
      "/stays/nautilus/nautilus19.jpg",
      "/stays/nautilus/nautilus20.jpg",
      "/stays/nautilus/nautilus21.jpg",
      "/stays/nautilus/nautilus22.jpg",
      "/stays/nautilus/nautilus23.jpg",
      "/stays/nautilus/nautilus24.jpg",
      "/stays/nautilus/nautilus25.jpg",
    ],
  },
  {
    id: "park-avenue-2",
    name: "Park Avenue 2",
    subtitle: "Miami Beach · South Beach",
    neighborhood: "Miami Beach",
    cardTagline: "4 bed · 3.5 bath · 5,000 sq ft",
    lede:
      "Four-story contemporary townhome at the north end of South Beach — rooftop terrace with plunge pool, steps from the Bass, the beach, and the Convention Center.",
    description:
      "This contemporary chic four-story townhome sits at the north end of South Beach in Miami Beach, within walking distance of the Bass Museum of Art, the ocean, entertainment districts, and the Miami Beach Convention Center. Rooftop terrace with plunge pool, top-of-the-line appliances, and a location suited to art, beach, and nightlife.",
    facts: [
      { label: "Location", value: "South Beach, Miami Beach" },
      { label: "Property size", value: "5,000 sq ft" },
      { label: "Bedrooms", value: "4" },
      { label: "Bathrooms", value: "3.5" },
      { label: "Max guests", value: "8" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Four levels with rooftop terrace and plunge pool",
      "Walkable to Bass Museum, beach, dining, and Convention Center",
      "Waterfront access with dock; balcony bay views",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Waterfront",
      "Boat dock",
    ],
    policyNotes: [
      "Maximum guests: 8.",
      "Children and pets allowed. Events allowed. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/parkavenue2/parkavenue2-1.jpg",
      "/stays/parkavenue2/parkavenue2-2.jpg",
      "/stays/parkavenue2/parkavenue2-3.jpg",
      "/stays/parkavenue2/parkavenue2-4.jpg",
      "/stays/parkavenue2/parkavenue2-5.jpg",
      "/stays/parkavenue2/parkavenue2-6.jpg",
      "/stays/parkavenue2/parkavenue2-7.jpg",
      "/stays/parkavenue2/parkavenue2-8.jpg",
      "/stays/parkavenue2/parkavenue2-9.jpg",
      "/stays/parkavenue2/parkavenue2-10.jpg",
      "/stays/parkavenue2/parkavenue2-11.jpg",
      "/stays/parkavenue2/parkavenue2-12.jpg",
      "/stays/parkavenue2/parkavenue2-13.jpg",
      "/stays/parkavenue2/parkavenue2-14.jpg",
      "/stays/parkavenue2/parkavenue2-15.jpg",
      "/stays/parkavenue2/parkavenue2-16.jpg",
      "/stays/parkavenue2/parkavenue2-17.jpg",
      "/stays/parkavenue2/parkavenue2-18.jpg",
      "/stays/parkavenue2/parkavenue2-19.jpg",
      "/stays/parkavenue2/parkavenue2-20.jpg",
      "/stays/parkavenue2/parkavenue2-21.jpg",
      "/stays/parkavenue2/parkavenue2-22.jpg",
      "/stays/parkavenue2/parkavenue2-23.jpg",
      "/stays/parkavenue2/parkavenue2-24.jpg",
      "/stays/parkavenue2/parkavenue2-25.jpg",
      "/stays/parkavenue2/parkavenue2-26.jpg",
      "/stays/parkavenue2/parkavenue2-27.jpg",
      "/stays/parkavenue2/parkavenue2-28.jpg",
      "/stays/parkavenue2/parkavenue2-29.jpg",
      "/stays/parkavenue2/parkavenue2-30.jpg",
      "/stays/parkavenue2/parkavenue2-31.jpg",
    ],
  },
  {
    id: "perla",
    name: "Perla",
    subtitle: "Miami Shores · waterfront",
    neighborhood: "Miami Shores",
    cardTagline: "6 bed · 4.5 bath · 5,000 sq ft",
    lede:
      "Waterfront Miami Shores villa with wide-bay access for yachts up to ~60 ft, private pool, sundeck, and 24/7 concierge meet-and-greet.",
    description:
      "A pearl of a Miami villa on the water — close to the Design District, Wynwood, and about ten minutes from Miami Beach. A modern take on nostalgic Art Deco from the late 1980s: wide-bay access without fixed bridges, ideal for mooring up to a 60-foot yacht. Sundeck upstairs and a very private pool area for lounging in seclusion. Outdoor bar and barbecue, pool table inside, and soaring ceilings with state-of-the-art finishes. Upon arrival, concierge meets you at the villa for a full walkthrough and keys; after that, communication is as hands-on or discreet as you prefer — expert tips, reservations, and VIP services available 24/7.",
    facts: [
      { label: "Location", value: "Miami Shores" },
      { label: "Property size", value: "5,000 sq ft" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "4.5" },
      { label: "Max guests", value: "14" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Dock for large yachts; wide bay without fixed bridges",
      "Private pool deck, outdoor bar & BBQ, and interior entertaining spaces",
      "Concierge meet-and-greet plus optional 24/7 VIP support",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
    ],
    policyNotes: [
      "Maximum guests: 14.",
      "Children and pets allowed. Smoking not permitted.",
      "The guest who books must stay at the home and provide photo ID.",
      "No parties, events, DJs, or loud music outside.",
      "Maximum four cars in the driveway; no street parking. Smoking outside only. Violations may result in immediate removal without refund.",
    ],
    galleryImages: [
      "/stays/perla/perla1.jpg",
      "/stays/perla/perla2.jpg",
      "/stays/perla/perla3.jpg",
      "/stays/perla/perla4.jpg",
      "/stays/perla/perla5.jpg",
      "/stays/perla/perla6.jpg",
      "/stays/perla/perla7.jpg",
      "/stays/perla/perla8.jpg",
      "/stays/perla/perla9.jpg",
      "/stays/perla/perla10.jpg",
      "/stays/perla/perla12.jpg",
      "/stays/perla/perla13.jpg",
      "/stays/perla/perla14.jpg",
      "/stays/perla/perla15.jpg",
      "/stays/perla/perla16.jpg",
      "/stays/perla/perla17.jpg",
      "/stays/perla/perla18.jpg",
      "/stays/perla/perla19.jpg",
      "/stays/perla/perla20.jpg",
      "/stays/perla/perla21.jpg",
      "/stays/perla/perla22.jpg",
      "/stays/perla/perla23.jpg",
      "/stays/perla/perla24.jpg",
      "/stays/perla/perla25.jpg",
      "/stays/perla/perla26.jpg",
      "/stays/perla/perla27.jpg",
      "/stays/perla/perla28.webp",
      "/stays/perla/perla29.jpg",
      "/stays/perla/perla30.jpg",
      "/stays/perla/perla31.jpg",
      "/stays/perla/perla32.jpg",
      "/stays/perla/perla33.jpg",
    ],
  },
  {
    id: "placida",
    name: "Placida",
    subtitle: "Venetian Islands · waterfront",
    neighborhood: "Venetian Islands",
    cardTagline: "8 bed · 7.5 bath · 7,800 sq ft",
    lede:
      "Three-story Venetian Islands estate — 7,800 sq ft with game and movie rooms, panoramic bay views, and a property-length lap pool.",
    description:
      "Magnificent waterfront villa with three stories, 7,800 square feet, eight bedrooms, seven and a half baths, game room, movie room, and sweeping bay views through panoramic impact windows and oversized terraces. Remodeled in 2017 with state-of-the-art finishes: massive eat-in chef’s kitchen, oversized jacuzzi, and a new lap pool along the full length of the property — drenched in South Florida sunshine.",
    facts: [
      { label: "Location", value: "Venetian Islands" },
      { label: "Property size", value: "7,800 sq ft" },
      { label: "Bedrooms", value: "8" },
      { label: "Bathrooms", value: "7.5" },
      { label: "Max guests", value: "16" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Panoramic bay views from impact glass and deep terraces",
      "Game and movie rooms; chef’s kitchen",
      "Resort-length lap pool and oversized spa",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
    ],
    policyNotes: [
      "Maximum guests: 16.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/placida/placida1.jpg",
      "/stays/placida/placida2.jpg",
      "/stays/placida/placida3.jpg",
      "/stays/placida/placida4.jpg",
      "/stays/placida/placida5.jpg",
      "/stays/placida/placida6.jpg",
      "/stays/placida/placida7.jpg",
      "/stays/placida/placida8.jpg",
      "/stays/placida/placida9.jpg",
      "/stays/placida/placida10.jpg",
      "/stays/placida/placida11.jpg",
      "/stays/placida/placida12.jpg",
      "/stays/placida/placida13.jpg",
      "/stays/placida/placida14.jpg",
      "/stays/placida/placida15.jpg",
      "/stays/placida/placida16.jpg",
      "/stays/placida/placida17.jpg",
      "/stays/placida/placida18.jpg",
      "/stays/placida/placida19.jpg",
      "/stays/placida/placida20.jpg",
      "/stays/placida/placida21.jpg",
      "/stays/placida/placida22.jpg",
      "/stays/placida/placida23.jpg",
      "/stays/placida/placida24.jpg",
      "/stays/placida/placida25.jpg",
      "/stays/placida/placida26.jpg",
      "/stays/placida/placida27.jpg",
      "/stays/placida/placida28.jpg",
      "/stays/placida/placida29.jpg",
      "/stays/placida/placida30.jpg",
      "/stays/placida/placida31.jpg",
      "/stays/placida/placida32.jpg",
      "/stays/placida/placida33.jpg",
      "/stays/placida/placida34.jpg",
      "/stays/placida/placida35.jpg",
      "/stays/placida/placida36.jpg",
      "/stays/placida/placida37.jpg",
      "/stays/placida/placida38.jpg",
      "/stays/placida/placida39.jpg",
    ],
  },
  {
    id: "soleil",
    name: "Soleil",
    subtitle: "Venetian Islands · bayfront",
    neighborhood: "Venetian Islands",
    cardTagline: "6 bed · 8.5 bath · 8,000 sq ft",
    lede:
      "Modern bayfront mansion with southern exposure, rooftop glass-wall pool, theater, and 360° terrace views over the skyline and Biscayne Bay.",
    description:
      "Warm, modern bayfront home with uncompromising luxury details. Southern exposure with Miami skyline and Biscayne Bay views. Sophisticated European design, white oak floors, soaring ceilings, and a one-of-a-kind rooftop glass-wall pool. Expansive terrace with 360° views, home theater, fireplace, private top-floor artist studio/office with views, uniquely lit glass-door elevator, and more. Minutes from South Beach, Lincoln Road, arts and entertainment, and the Design District.",
    facts: [
      { label: "Location", value: "Venetian Islands" },
      { label: "Property size", value: "8,000 sq ft" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "8.5" },
      { label: "Max guests", value: "12" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Rooftop glass-wall pool and wraparound terrace views",
      "Theater, fireplace, and private studio/office on the top floor",
      "Glass elevator and European-inspired interiors",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
    ],
    policyNotes: [
      "Maximum guests: 12.",
      "Children allowed. Pets not permitted. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/soleil/soleil1.jpg",
      "/stays/soleil/soleil2.jpg",
      "/stays/soleil/soleil3.jpg",
      "/stays/soleil/soleil4.jpg",
      "/stays/soleil/soleil5.jpg",
      "/stays/soleil/soleil6.jpg",
      "/stays/soleil/soleil7.jpg",
      "/stays/soleil/soleil8.jpg",
      "/stays/soleil/soleil9.jpg",
      "/stays/soleil/soleil10.jpg",
      "/stays/soleil/soleil11.jpg",
      "/stays/soleil/soleil12.jpg",
      "/stays/soleil/soleil13.jpg",
      "/stays/soleil/soleil14.jpg",
      "/stays/soleil/soleil15.jpg",
      "/stays/soleil/soleil16.jpg",
      "/stays/soleil/soleil17.jpg",
      "/stays/soleil/soleil18.jpg",
      "/stays/soleil/soleil19.jpg",
      "/stays/soleil/soleil20.jpg",
      "/stays/soleil/soleil21.jpg",
      "/stays/soleil/soleil22.jpg",
      "/stays/soleil/soleil23.jpg",
      "/stays/soleil/soleil24.jpg",
      "/stays/soleil/soleil25.jpg",
      "/stays/soleil/soleil26.jpg",
      "/stays/soleil/soleil27.jpg",
      "/stays/soleil/soleil28.jpg",
      "/stays/soleil/soleil29.jpg",
      "/stays/soleil/soleil30.jpg",
      "/stays/soleil/soleil31.jpg",
      "/stays/soleil/soleil32.jpg",
      "/stays/soleil/soleil33.jpg",
      "/stays/soleil/soleil34.jpg",
      "/stays/soleil/soleil35.jpg",
      "/stays/soleil/soleil36.jpg",
      "/stays/soleil/soleil37.jpg",
      "/stays/soleil/soleil38.jpg",
      "/stays/soleil/soleil39.jpg",
    ],
  },
  {
    id: "teaka",
    name: "Teaka",
    subtitle: "Venetian Islands · waterfront",
    neighborhood: "Venetian Islands",
    cardTagline: "6 bed · 5.5 bath · 6,000 sq ft",
    lede:
      "Balinese-meets-modern waterfront villa — 60 ft of frontage, rooftop deck, pool, fire pit, hot tub, and basketball court.",
    description:
      "A fusion of Balinese and modern design on the Venetian Islands. Sixty feet of waterfront, a pool, and an expansive rooftop deck. Soaring ceilings, large bay windows, Bangkirai wood details, chef’s kitchen, and an entertainment room with pool table and marble bar. Lush landscaping frames the fire pit, hot tub, outdoor dining, and a basketball court. 21st-century luxury with Balinese detail — day-to-night views across Miami Beach and Downtown.",
    facts: [
      { label: "Location", value: "Venetian Islands" },
      { label: "Property size", value: "6,000 sq ft" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "5.5" },
      { label: "Max guests", value: "10" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Balinese-inspired details with modern entertaining spaces",
      "Rooftop deck, pool, fire pit, spa, and outdoor kitchen",
      "Basketball court and 60 ft of waterfront",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
      "Rooftop patio",
    ],
    policyNotes: [
      "Maximum guests: 10.",
      "Children allowed. Pets not permitted. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/teaka/teaka1.jpg",
      "/stays/teaka/teaka2.jpg",
      "/stays/teaka/teaka3.jpg",
      "/stays/teaka/teaka4.jpg",
      "/stays/teaka/teaka5.jpg",
      "/stays/teaka/teaka6.jpg",
      "/stays/teaka/teaka7.jpg",
      "/stays/teaka/teaka8.jpg",
      "/stays/teaka/teaka9.jpg",
      "/stays/teaka/teaka10.jpg",
      "/stays/teaka/teaka11.jpg",
      "/stays/teaka/teaka12.jpg",
      "/stays/teaka/teaka13.jpg",
      "/stays/teaka/teaka14.jpg",
      "/stays/teaka/teaka15.jpg",
      "/stays/teaka/teaka16.jpg",
      "/stays/teaka/teaka17.jpg",
      "/stays/teaka/teaka18.jpg",
      "/stays/teaka/teaka19.jpg",
      "/stays/teaka/teaka20.jpg",
      "/stays/teaka/teaka21.jpg",
      "/stays/teaka/teaka22.jpg",
      "/stays/teaka/teaka23.jpg",
    ],
  },
  {
    id: "vista",
    name: "Vista",
    subtitle: "Miami Beach · gated island",
    neighborhood: "Miami Beach",
    cardTagline: "5 bed · 4 bath · 4,200 sq ft",
    lede:
      "Private peninsula estate with ocean and downtown views — 220 ft waterfront, 100+ ft yacht dock with lift, guest house, and guard-gated entry.",
    description:
      "Stunning ocean and skyline views from your private peninsula. Electric Downtown and Miami Beach views with 220 feet of waterfront, an oversized dock for a 100 ft yacht and boat lift. Expansive great rooms with vaulted ceilings, updated kitchen, impact windows and doors throughout — four bedrooms in the main house plus one bed / one bath in a detached guest house. Ample driveway with porte-cochère and electric gate. Exclusive guard-gated island community.",
    facts: [
      { label: "Location", value: "Miami Beach · gated island" },
      { label: "Property size", value: "4,200 sq ft" },
      { label: "Bedrooms", value: "5" },
      { label: "Bathrooms", value: "4" },
      { label: "Max guests", value: "12" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "220 ft waterfront with large-yacht dock and lift",
      "Main house plus detached guest house; porte-cochère entry",
      "Guard-gated island with panoramic ocean and city views",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Balcony",
      "Pool",
      "Waterfront",
      "Boat dock",
      "Outdoor kitchen",
    ],
    policyNotes: [
      "Maximum guests: 12.",
      "Children and pets allowed. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/vista/vista1.jpg",
      "/stays/vista/vista2.jpg",
      "/stays/vista/vista3.jpg",
      "/stays/vista/vista4.jpg",
      "/stays/vista/vista5.jpg",
      "/stays/vista/vista6.jpg",
      "/stays/vista/vista7.jpg",
      "/stays/vista/vista8.jpg",
      "/stays/vista/vista9.jpg",
      "/stays/vista/vista10.jpg",
      "/stays/vista/vista11.jpg",
      "/stays/vista/vista12.jpg",
      "/stays/vista/vista13.jpg",
      "/stays/vista/vista14.jpg",
      "/stays/vista/vista15.jpg",
      "/stays/vista/vista16.jpg",
      "/stays/vista/vista17.jpg",
      "/stays/vista/vista18.jpg",
      "/stays/vista/vista19.jpg",
      "/stays/vista/vista20.jpg",
      "/stays/vista/vista21.jpg",
      "/stays/vista/vista22.jpg",
      "/stays/vista/vista23.jpg",
      "/stays/vista/vista24.jpg",
      "/stays/vista/vista25.jpg",
    ],
  },
  {
    id: "zuma",
    name: "Zuma",
    subtitle: "Golden Beach · oceanfront",
    neighborhood: "Golden Beach",
    cardTagline: "9 bed · 9 bath · 9,500 sq ft",
    lede:
      "Nine-thousand-five-hundred-square-foot Golden Beach icon — three levels, ocean views, elevator, transparent pool waterfall from the master, and magazine-worthy architecture.",
    description:
      "Featured in magazines and global design festivals: three floors, direct ocean views, elevator, open yet private layout, two-story windows, huge terraces, reflective pond, and a one-of-a-kind transparent pool with a waterfall cascading from the master suite. Walking distance to a children’s park, beach access, and a dedicated local police presence. Quiet versus South Beach nightlife; convenient to Hard Rock Stadium north and Wynwood south.",
    facts: [
      { label: "Location", value: "Golden Beach" },
      { label: "Property size", value: "9,500 sq ft" },
      { label: "Bedrooms", value: "9" },
      { label: "Bathrooms", value: "9" },
      { label: "Max guests", value: "14" },
      { label: "Check-in", value: "After 4:00 pm" },
      { label: "Check-out", value: "After 11:00 am" },
    ],
    highlights: [
      "Direct ocean views across three levels with elevator",
      "Transparent pool, waterfall feature, and reflective pond",
      "Family-friendly Golden Beach near parks, beach, and security patrols",
    ],
    inclusions: [
      "Wi-Fi",
      "Coffee machine",
      "Hair dryer",
      "LED TV",
      "Pool",
    ],
    policyNotes: [
      "Maximum guests: 14.",
      "Children allowed. Pets not permitted. Events not permitted. Smoking not permitted.",
    ],
    galleryImages: [
      "/stays/zuma/zuma1.jpg",
      "/stays/zuma/zuma2.jpg",
      "/stays/zuma/zuma3.jpg",
      "/stays/zuma/zuma4.jpg",
      "/stays/zuma/zuma5.jpg",
      "/stays/zuma/zuma6.jpg",
      "/stays/zuma/zuma7.jpg",
      "/stays/zuma/zuma8.jpg",
      "/stays/zuma/zuma9.jpg",
      "/stays/zuma/zuma10.jpg",
      "/stays/zuma/zuma11.jpg",
      "/stays/zuma/zuma12.jpg",
      "/stays/zuma/zuma13.jpg",
      "/stays/zuma/zuma14.jpg",
      "/stays/zuma/zuma15.jpg",
      "/stays/zuma/zuma16.jpg",
      "/stays/zuma/zuma17.jpg",
      "/stays/zuma/zuma18.jpg",
      "/stays/zuma/zuma19.jpg",
      "/stays/zuma/zuma20.jpg",
      "/stays/zuma/zuma21.jpg",
      "/stays/zuma/zuma22.jpg",
      "/stays/zuma/zuma23.jpg",
      "/stays/zuma/zuma24.jpg",
      "/stays/zuma/zuma25.jpg",
      "/stays/zuma/zuma26.jpg",
    ],
  },
];

const VILLA_BY_SLUG = new Map(VILLAS.map((villa) => [villa.id, villa] as const));

export function getVillaBySlug(slug: string): Villa | undefined {
  return VILLA_BY_SLUG.get(slug);
}
